### ISSUE TITLE
Forgot password in login page

### ISSUE THREAD

**Issue by sic4change** [benwinding/react-admin-firebase#101]
How can I add a button or link in LoginForm that detects click and perform a request to firebase to send password reset email?

firebase.auth().sendPasswordResetEmail('text in email input');

Regards

**Comment by benwinding** [comment]
Hey @sic4change,

Yes this has been a pain for a lot of us, so I added a component to this repository `<CustomForgotPassword>`, [src file is here](https://github.com/benwinding/react-admin-firebase/blob/56434cb67999b387d3b486ff4fa214fbdc0379bf/src-demo/src/CustomForgotPassword.js) just add it where every you want to be able to send a password reset email.

Also, if you want to customise the Email text, you need to edit the email settings in the Firebase console. 

Demo

![Peek 2020-04-11 09-13](https://user-images.githubusercontent.com/11782590/79029755-f14f2300-7bd4-11ea-9df0-e724e1a5cc05.gif)

Cheers,
Ben

**Comment by sic4change** [comment]
Perfect!! It is working. 
Thanks.

Regards
