### ISSUE TITLE
Firebase Authentication??

### ISSUE THREAD

**Issue by benwinding** [benwinding/react-admin-firebase#11]
This should use Firebase Authentication to login!!

_Note to self: do this ^_

**Comment by benwinding** [comment]
This is done!

Users are now able to login, via email and password. If they exist on the firebase authentication table. This means you can lock off the entire database with rules which only allow authenticated users

- 5726e11b0c09f4de32ae944e7932fc26ff22423e

**Comment by bgberk** [comment]
Works great locally, but I'm not able to get it to work in production. Deployed the minimal example project with my own Firebase credentials to Firebase Hosting and Zeit Now, but both give the snackbar "Login error: invalid credentials". Maybe something with the CRA build process?

**Comment by benwinding** [comment]
Hi @bgberk,
We've just fixed an issue a few days ago with `create-react-app` version `2.1.8`.
Thanks for the update, can you try using the latest version of **react-admin-firebase** `0.5.3`?
Cheers,
Ben

**Comment by bgberk** [comment]
Yes, this is my package.json: 
`{`
`  "name": "name",`
`  "version": "0.1.0",`
`  "private": true,`
`  "dependencies": {`
`    "react": "^16.8.6",`
`    "react-admin": "^2.9.0",`
`    "react-admin-firebase": "^0.5.3",`
`    "react-dom": "^16.8.6",`
`    "react-scripts": "2.1.8"`
`  },`
`  "scripts": {`
`    "start": "PORT=3006 react-scripts start",`
`    "build": "react-scripts build",`
`    "now-build": "react-scripts build",`
`    "test": "react-scripts test",`
`    "eject": "react-scripts eject"`
`  },`
`  "eslintConfig": {`
`    "extends": "react-app"`
`  },`
`  "browserslist": [`
`    ">0.2%",`
`    "not dead",`
`    "not ie <= 11",`
`    "not op_mini all"`
`  ]`
`}`
Same problem as before, unfortunately.

**Comment by benwinding** [comment]
`Login error: invalid credentials`, means it could be a configuration error, so can you please try some of the following things to see if this resolves the issue:
- Check that you have connected the correct domains to your firebase project in the `hosting` tab (you need to explicitly set these, or firebase won't allow your app to connect to firestore)
![Screenshot from 2019-05-09 14-09-49](https://user-images.githubusercontent.com/11782590/57427738-7531ba00-7264-11e9-810d-d4d785647baa.png)

- Try replacing the configuration object from firebase console (make sure it's the correct one)
```
  var firebaseConfig = {
    apiKey: "pqwionfoinaowfnoaiwnfoaoiwfnoinawf",
    .....
  };
```
- Try resetting your password through the firebase console
- Try Remove `node_modules` then `yarn` or `npm i` (it could still be cached locally)

Try each one of these and test, sounds like it could be the first item if you're deploying to `Zeit Now`

**Comment by bgberk** [comment]
I agree that it's got to be a configuration error, somehow. I've done each of the things you suggested, including checking the domain (just using the generated firebaseapp.com URL at this point). Is it something about my development environment, i.e. you can get the example project hosted on Firebase? Thanks for the support.

**Comment by benwinding** [comment]
It's deployed to Firebase here: [https://react-admin-firebase-1.web.app/#/posts](https://react-admin-firebase-1.web.app/#/posts)

username: test@example.com
password: test@example.com

The source code is updated at [https://github.com/benwinding/react-admin-firebase-demo](https://github.com/benwinding/react-admin-firebase-demo).

Let me know if it works out for you.

**Comment by bgberk** [comment]
This is not an issue with this package-- I created a new Firebase project and deployed the original code in question without errors, so there's something wrong with the configuration in my existing project somehow. I'll continue to troubleshoot, but in case anyone else is having the same problem, it might just be best to migrate to a new project. 
Thanks for the support!

**Comment by benwinding** [comment]
Oh no worries!
Well, one more thing to check is the name of the exported firebase configuration in the example it used check that the configuration is correctly being read and placed into the Dataprovider.

``` js
export const firebaseConfig = { // Check this variable name
  apiKey: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
  authDomain: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
  databaseURL: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
  projectId: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
  storageBucket: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
  messagingSenderId: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
};
```

``` js
// Matches this import here
import { firebaseConfig } from './FIREBASE_CONFIG';

const authProvider = FirebaseAuthProvider(firebaseConfig);
```

Hope it works out anyway!
