### ISSUE TITLE
Filter doesn't work for boolean

### ISSUE THREAD

**Issue by MichalKalita** [benwinding/react-admin-firebase#111]
Hi, filtering by boolean value doesn't work :(

React admin code
```tsx
<ReferenceInput
 source="shipping_id"
 reference="shipping"
 filter={{ enable_for_all_products: false }} 
>
 <SelectInput
  label="Shipping"
  required
 />
</ReferenceInput>
```

In firestore `shipping` collections exists docs with `enable_for_all_products` value boolean false.

Expected result: filtered docs should be visible in react admin

Actual result: SelectInput is empty. When I remove filter, all docs are in SelectInput.

**Comment by benwinding** [comment]
Thanks for reporting this, it was only filtering strings before. Now it will filter `string`, `boolean`, `number` values. 

Should be deployed as version: `3.1.12`

Also added unit-tests to ensure it doesn't break again!

https://github.com/benwinding/react-admin-firebase/blob/b9b19de90ca42991a06022bf2bc6708208e12102/tests/arrayHelpers.filtering.spec.ts#L74-L86
