### ISSUE TITLE
Error when Filter using ReferenceArrayInput

### ISSUE THREAD

**Issue by aaronat1** [benwinding/react-admin-firebase#112]
I have a filter, for example:
 ```
<Filter {...props} >
        <TextInput label="Name" source="name" allowEmpty alwaysOn resettable/>
        <ReferenceArrayInput label="Group" source="group" reference="groups"  allowEmpty alwaysOn>
          <AutocompleteArrayInput optionText="group" />
        </ReferenceArrayInput>
      </Filter>
```
After select a value in AutocompleteArrayInput application crash and login page is showed.

Thanks,
Regards

**Comment by benwinding** [comment]
Hi @aaronat1, 

What version of the library are you using? Try the most recent version, as unexpected logouts were addressed in issue #91.

I'm not sure how to replicate the problem you have, can you share the browser `console` error output. 

Or even better, you could create a [stackblitz](https://stackblitz.com/edit/react-admin-ex1) to demonstrate the problem.

Cheers,
Ben

**Comment by aaronat1** [comment]
I am using 3.3.1 version.
In my firestore I have an object called campaign that includes an array called  group.
I want to filter campaigns  by grup selected. In filter I can selecte several groups. I am using  ReferenceArrayInput witn AutocompleteArrayInput inside:

```
<Filter {...props} >
       <TextInput label="Name" source="name" allowEmpty alwaysOn resettable/>
       <ReferenceArrayInput label="Group" source="group" reference="groups"  allowEmpty alwaysOn>
         <AutocompleteArrayInput optionText="group" />
       </ReferenceArrayInput>
     </Filter>
```
This filter is used in campaign List

` <List {...props} filters={<CampaignFilter />} actions={<ListActions/>} bulkActionButtons={false}>`

When I select a group with AutocompleteArrayInput my web crashs and login page is showed. I can not see any log message.

Thanks

Regards

**Comment by benwinding** [comment]
Sorry, I'm not familiar with using `<ReferenceArrayInput>` perhaps someone else might have some advice?

Anyway you can try the following:
- Update to 3.1.16 (latest version) see if that helps in some way
- Enable logging by passing in `logging: true` in the options to the dataprovider

Hopefully that gets you closer to fixing it.

**Comment by aaronat1** [comment]
Thanks @benwinding. I have update to 3.1.17 and my web application does not crash. But the filter does not work very well. 

I atach several images to show the behaviour:
![Captura de pantalla 2020-04-28 a las 10 22 01](https://user-images.githubusercontent.com/8913552/80470672-3e9ff400-893a-11ea-90d1-85c2cead1f8c.png)
![Captura de pantalla 2020-04-28 a las 10 22 24](https://user-images.githubusercontent.com/8913552/80470697-43fd3e80-893a-11ea-9e4d-fe33ed08ef3a.png)

As you can see I am filtering by grup. Result is wrong. I shoud see this result:
![Captura de pantalla 2020-04-28 a las 10 22 01](https://user-images.githubusercontent.com/8913552/80470940-9c344080-893a-11ea-8e03-caebc9248acc.png)

I think that the problem is related with object position in the array.

Regards

**Comment by sethcwhiting** [comment]
Side note: I also had to update my react-admin package to the latest version.

**Comment by aaronat1** [comment]
Yeah @sethcwhiting . Your solution works!!  I have updated to react-admin to the latest version and react-admin-firebase to the latest verstion. But, I have a problem now. When I deploy my projects in firebase hosting, my web application works wrong. 

Regards.
