### ISSUE TITLE
Error version 3.1.17 when deploy in Firebase Hosting

### ISSUE THREAD

**Issue by sic4change** [benwinding/react-admin-firebase#116]
Hi!
Thanks!! It is very nice project.
I have a problem. My project was running in Firebase but I have updated to 3.1.17 and my project is not working fine. All time I have received a Notification "TypeError: t is not a function" and my coleccions from Firestore is not showing.
![Captura de pantalla 2020-04-28 a las 22 05 42](https://user-images.githubusercontent.com/48917076/80537756-75a6f180-899c-11ea-9f7e-16f657929f44.png)

Can you help me?

Log from Javascript console in Chrome. Error says something about invalid credentials, but I am logged in...
.....
🔥r-a-f:  resourceManager.applyQuery() ... 
{collection: t, collectionQuery: "-", collref: t}
collection: t {pE: e, firestore: e, EE: undefined, BE: t}
collectionQuery: "-"
collref: t {pE: e, firestore: e, EE: undefined, BE: t}
__proto__: Object

🔥r-a-f:  HandleAuthLogin: invalid credentials 
{errorHttp: {…}}
errorHttp:
json: undefined
message: "TypeError: t is not a function"
status: 409
__proto__: Object
__proto__: Object
....

In my machine project is working fine. On the other hand...when run in firebase:

`firebase serve --only hosting`
 or
`firebase deploy --only hosting`

I can see the errors.

Thanks.
Regards

**Comment by benwinding** [comment]
Hi @sic4change,

Interesting, this seems to be a problem with react-admin (see this issue https://github.com/marmelab/react-admin/issues/4337)

Fix it by upgrading to `react-admin@3.3.3` https://github.com/marmelab/react-admin/issues/4337#issuecomment-606110988

I've just tested and it seems to work with `firebase serve --only hosting`, but let me know if there's any problems.

Cheers,
Ben

**Comment by benwinding** [comment]
- Have you tried a hard refresh? `ctrl + r` or `cmd + r`
- Try a different browser Chrome and Firefox, try incognito and deleting application cache
- Try deleting `node_modules` and `yarn` again (annoying but this sometimes works)
- Try deleting `build` or `dist` folder

When I was testing it in Chrome, it only did it on the initial page load
- `mydomain.com` (showed the error)
- `mydomain.com#/login` (reloaded page and had no error, probably the web worker caching)

**Comment by sic4change** [comment]
Thank for your help @benwinding, but your solution not working.

yarn start

http://192.168.1.51:3333 => work perfect.

yarn build
firebase serve --only hosting => the same problem, not working fine

I do not undertand the problem...
Regards

**Comment by aaronat1** [comment]
I am having the same problem when updated react-admin and react-admin-firebase to the latest version. Regards

**Comment by benwinding** [comment]
Well apparently it's fixed by upgrading to react-admin@3.3.3 as shown in this issue marmelab/react-admin#4337 (comment). 

You might need to clear you browser cache after doing this though.

If you make a stackblitz example showing the issue, I will be able to provide more help

Try editing this one to demonstrate the issue: https://stackblitz.com/github/qgnirypbj

**Comment by aaronat1** [comment]
Thanks @benwinding 

I have cleared my google chrome and mozilla firefox cache many times and the problem persits when deploy to firebase.

I'm going to try to share my code with you.

Regards

**Comment by benwinding** [comment]
Updating to `"react-scripts": "3.4.1"` to the latest version in your `package.json` file seems to fix this problem.

**Comment by sic4change** [comment]
Yeah!! Working.
Thanks.
Regards
