### ISSUE TITLE
HTTP 400 error from data provider triggering logout in FirebaseAuthProvider

### ISSUE THREAD

**Issue by crappycocco** [benwinding/react-admin-firebase#117]
public HandleAuthError(errorHttp: messageTypes.HttpErrorType) {
    log("HandleAuthLogin: invalid credentials", { errorHttp });
    const status = !!errorHttp && errorHttp.status;
    if (status === 409 || status === 200) {
      return Promise.resolve("API is authenticated");
    }
    **return Promise.reject("Recieved authentication error from API");**
  }

**Comment by crappycocco** [comment]
Error: ra.notification.data_provider_error
    at validateResponseFormat (validateResponseFormat.js:7)
    at useDataProvider.js:353
console.<computed> @ index.js:1
(anonymous) @ useDataProvider.js:367
Promise.catch (async)
performQuery @ useDataProvider.js:364
doQuery @ useDataProvider.js:195
(anonymous) @ useDataProvider.js:172
(anonymous) @ useQueryWithStore.js:130
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
AuthProvider.ts:66 🔥r-a-f:  HandleAuthLogin: invalid credentials {errorHttp: Error: ra.notification.data_provider_error
    at validateResponseFormat (http://localhost:3333/rea…}

**Comment by crappycocco** [comment]
Error: ra.notification.data_provider_error
    at validateResponseFormat (validateResponseFormat.js:7)
    at useDataProvider.js:353
console.<computed> @ index.js:1
(anonymous) @ useDataProvider.js:367
Promise.catch (async)
performQuery @ useDataProvider.js:364
doQuery @ useDataProvider.js:195
(anonymous) @ useDataProvider.js:172
(anonymous) @ useQueryWithStore.js:130
commitHookEffectListMount @ react-dom.development.js:19731
commitPassiveHookEffects @ react-dom.development.js:19769
callCallback @ react-dom.development.js:188
invokeGuardedCallbackDev @ react-dom.development.js:237
invokeGuardedCallback @ react-dom.development.js:292
flushPassiveEffectsImpl @ react-dom.development.js:22853
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushPassiveEffects @ react-dom.development.js:22820
performSyncWorkOnRoot @ react-dom.development.js:21737
(anonymous) @ react-dom.development.js:11089
unstable_runWithPriority @ scheduler.development.js:653
runWithPriority$1 @ react-dom.development.js:11039
flushSyncCallbackQueueImpl @ react-dom.development.js:11084
flushSyncCallbackQueue @ react-dom.development.js:11072
discreteUpdates$1 @ react-dom.development.js:21893
discreteUpdates @ react-dom.development.js:806
dispatchDiscreteEvent @ react-dom.development.js:4168
AuthProvider.ts:66 🔥r-a-f:  HandleAuthLogin: invalid credentials {errorHttp: Error: ra.notification.data_provider_error
    at validateResponseFormat (http://localhost:3333/rea…}

**Comment by benwinding** [comment]
Hey @crappycocco ,

Thanks for reporting this, looks like there's a lot of HTTP request codes to handle.

This file from the firebase SDK shows a few major ones.

https://github.com/firebase/firebase-js-sdk/blob/9f109f85ad0d99f6c13e68dcb549a0b852e35a2a/packages/functions/src/api/error.ts

So I've handled most of them in this function here:
https://github.com/benwinding/react-admin-firebase/blob/e4f5b9df2e16085141d46792a29dcbb6bb7b7d7c/src/providers/AuthProvider.ts#L68-L98

Should be deployed in `react-admin-firebase@3.1.17`

Let me know if it works for you.
Cheers,
Ben

**Comment by crappycocco** [comment]
I changed my uname and still shows crappycocco :D, will update the username now (hopefully) this issue is still reachable. Thanks for the fix, I will test and get back to you, thanks for being so responsive @benwinding.

**Comment by crappycocco** [comment]
@benwinding now the 401 response on the DataProvider is not logging the app out, is this expected. Previously any error (4xx, 5xx etc) were logging the app out.

**Comment by crappycocco** [comment]
I am manually handling the errors using a CustomDataProvider (please see the code for response error handling in my DataProvider).

return httpClient(url, options).then(response =>
            convertHTTPResponse(response, type, resource, params)
        ).catch((e) => {
            console.log("!!!!!!!!!!!!!!!!! DataProvider Error:" + JSON.stringify(e));
            if (e && e.status) {
                switch (e.status) {
                    case 401:
                        return Promise.reject("Authentication Error");
                        break;
                    case 500:
                        return Promise.reject("Internal Error");
                        break;
                    default:
                        return Promise.reject("Unknown Error, Please Try Again");
                        break;
                }
            }
        });

**Comment by benwinding** [comment]
Hey mate,

With the latest version; this is the current Auth checking code:

https://github.com/benwinding/react-admin-firebase/blob/0ae83768954a45fc80a305c6d8c2017cc8cd35be/src/providers/AuthProvider.ts#L75-L100

`401` should be logging out due to the unauthenticated error. Are you seeing any error output in the devtools console? Let me know what I should do to remedy this.

Cheers,
Ben

**Comment by crappycocco** [comment]
@benwinding your auth provider is working fine, I am just wondering about an earlier version behavior I was seeing where the data provider (REST API http errors) also triggered the firebaseauth provider to logout - was this a bug or an expected behavior?

**Comment by crappycocco** [comment]
Console errors
![Screen Shot 2020-05-10 at 1 18 41 PM](https://user-images.githubusercontent.com/41040576/81505929-e0bbc680-92c0-11ea-851d-32ed71ae9a55.png)

**Comment by crappycocco** [comment]
AuthProvider is logging the Auth error which was thrown by the DataProvider, but it is not doing logout.

**Comment by benwinding** [comment]
> I am just wondering about an earlier version behavior where I was seeing that the dataprovider (REST API which could return an http error) triggered the firebaseauth provider to logout - was this a bug or an expected behavior?

Yes this was expected behaviour. It should only logout if you're `unauthenticated` which can be triggered by viewing things you don't have access to, trying to add a document without access.

You're right it should of logged you out but the DataProvider was not returning the correct error code. Here's the fix below.

https://github.com/benwinding/react-admin-firebase/blob/9b176d7d75951d8ec33331881bd41e5ed91050da/src/providers/DataProvider.ts#L82-L85

Should be deployed in version `react-admin-firebase@3.1.21` let me know if that works.

Cheers,
Ben

**Comment by crappycocco** [comment]
@benwinding will this work with my custom DataProvider, I am using the below code for handling http errors (I know this is not your work, still ..)

catch((e) => {
            console.log("!!!!!!!!!!!!!!!!! DataProvider Error:" + JSON.stringify(e));
            if (e && e.status) {
                switch (e.status) {
                    case 401:
                        return Promise.reject("Authentication Error");
                    case 500:
                        return Promise.reject("Internal Error");
                    default:
                        return Promise.reject("Unknown Error, Please Try Again");
                }
            }
        });

**Comment by benwinding** [comment]
It was incorrectly implemented according to react-admin, but now it has been fixed to _rethrow_ HTTP errors in the DataProvider correctly.

You're DataProvider wrapper should catch those HTTP errors as intended.

Please see the next release `react-admin-firebase@3.1.22` and let me know how you go
