### ISSUE TITLE
createdate and lastupdate

### ISSUE THREAD

**Issue by macscripter** [benwinding/react-admin-firebase#12]
Hi,
Any chance to add createdate and lastupdate fields for insert/update in firebase? It would be very useful!

**Comment by benwinding** [comment]
Hi @macscripter!
Yes, that's a great idea, I'm currently looking into this, but I could use some help as it's not as simple as I thought. 
Have you got the document `insert/update` timestamps before using the client-side Firebase SDK? 
Cheers,
Ben

**Comment by macscripter** [comment]
Hi, @benwinding ,

It's very easy:

For apiCreate in firebaseDataProvider.ts:

`  public async apiCreate(
    resourceName: string,
    params: IParamsCreate
  ): Promise<IResponseCreate> {
    const r = await this.tryGetResource(resourceName);
    log("apiCreate", { resourceName, resource: r, params });
    const doc = await r.collection.add({
      ...params.data,
      createdate: firebase.firestore.FieldValue.serverTimestamp(),
      lastupdate: firebase.firestore.FieldValue.serverTimestamp()
    });
    return {
      data: {
        ...params.data,
        id: doc.id
      }
    };
  }`

For apiUpdate in firebaseDataProvider.ts:

`public async apiUpdate(
    resourceName: string,
    params: IParamsUpdate
  ): Promise<IResponseUpdate> {
    const id = params.id;
    delete params.data.id;
    const r = await this.tryGetResource(resourceName);
    log("apiUpdate", { resourceName, resource: r, params });
    r.collection.doc(id).update({
      ...params.data,
      lastupdate: firebase.firestore.FieldValue.serverTimestamp()
    });
    return {
      data: {
        ...params.data,
        id
      }
    };
  }`

And for apiUpdateMany in firebaseDataProvider.ts:

`public async apiUpdateMany(
    resourceName: string,
    params: IParamsUpdateMany
  ): Promise<IResponseUpdateMany> {
    delete params.data.id;
    const r = await this.tryGetResource(resourceName);
    log("apiUpdateMany", { resourceName, resource: r, params });
    const returnData = [];
    for (const id of params.ids) {
      r.collection
        .doc(id)
        .update({
          ...params.data,
          lastupdate: firebase.firestore.FieldValue.serverTimestamp()
        });
      returnData.push({
        ...params.data,
        id
      });
    }
    return {
      data: returnData
    };
  }`

Can you create a specific branch to commit this code?

**Comment by benwinding** [comment]
Thanks for your efforts @macscripter!
That's a nice and simple solution, I was initially thinking there was some kind of firebase native meta data we could use on the client, but it's only available from the firebase-admin...
Your solution was so simple that I just published the package as version `0.5.0`. 
Please, let me know if there's any issues, or if you have any other ideas.
Cheers,
Ben

**Comment by wendelsilverio** [comment]
I needed to disable automatic completion of **createdate** and **lastupdate** in the **RAFirebaseOptions disableMeta** configuration because the error `Cannot read properties of undefined (reading 'toLocaleString')` was occurring in the transition from record creation to editing after saving.

I noticed that the problem happens due to the values being filled in asynchronously with the server.

The log in my inspection had this format:
`lastupdate: __PRIVATE_ServerTimestampFieldValueImpl {_methodName: 'serverTimestamp'}`
