### ISSUE TITLE
View/Edit JWT Claims

### ISSUE THREAD

**Issue by Immortalin** [benwinding/react-admin-firebase#120]
Currently, the default Firebase Auth Users console lacks access to JWT Claims and those can only be viewed programmatically by invoking the API, can viewing/editing be supported in react-admin?

**Comment by benwinding** [comment]
Hi @Immortalin,

I'm pretty sure JWT claims cannot be modified on the client, you can decode and view them on the client using the UserToken. 
``` js
// Get custom claims using auth provider
const currentUser = authProvider('AUTH_GETCURRENT');
currentUser.getIdTokenResult()
  .then((idTokenResult) => {
     // Confirm the user is an Admin.
     if (!!idTokenResult.claims.admin) {
       // Show admin UI.
       showAdminUI();
     } else {
       // Show regular user UI.
       showRegularUI();
     }
  })
  .catch((error) => {
    console.log(error);
  });
```
But if you want to modify them, you need to do it using `firebase-admin` which is a server-side npm package and is usually included in a firebase-function.

Please see this link for more details:
https://firebase.google.com/docs/auth/admin/custom-claims#access_custom_claims_on_the_client

Cheers,
Ben

**Comment by Immortalin** [comment]
Do you think it can be added a field? It should be quite straightforward, being able to see the fields would greatly aid in debugging.

**Comment by benwinding** [comment]
Would be nice, I'm not sure how it could be done for other user that are not logged in though. 

Always open to suggestions and Pull Requests

**Comment by Immortalin** [comment]
That's a good point, didn't think of that. Oops.
