### ISSUE TITLE
Problem when create and update entity with image

### ISSUE THREAD

**Issue by sic4change** [benwinding/react-admin-firebase#122]
When I create an object, for example User with image I see and error message:

FirebaseError: [code=invalid-argument]: Function DocumentReference.update() called with invalid data. Unsupported field value: undefined (found in field background.src)

Then, user is not created and not updated in firestore.

Thanks.

Regards

**Comment by sic4change** [comment]
Solved,
It is neccesary change rules in Storage in Firebase to:

service firebase.storage {
  match /b/{bucket}/o {
    match /{allPaths=**} {
      allow read, write: if request.auth != null;
    }
  }
}

**Comment by benwinding** [comment]
Glad you got it solved!

**Comment by xididri** [comment]
@sic4change you are a life saver!
