### ISSUE TITLE
How to use realtime

### ISSUE THREAD

**Issue by RWOverdijk** [benwinding/react-admin-firebase#124]
I found the `watch` option and upon trying to use it noticed that it doesn't update my list when I make changes in the firestore console. How should this feature be used?

**Comment by benwinding** [comment]
Hey @RWOverdijk,
Sorry the `watch` feature needs some work. In an earlier version it was used with the RealtimeProvider, but that's no longer supported by `react-admin` I think? (related to this issue #57)
I'll have a look at re-implementing the `watch` feature in the next week or so.
Cheers,
Ben

**Comment by benwinding** [comment]
ra-realtime is only available in the premium version of react-admin, closing, will open again if needed
https://marmelab.com/ra-enterprise/modules/ra-realtime
