### ISSUE TITLE
suggestion: modify HandleAuthCheck in firebaseAuthProvider.ts

### ISSUE THREAD

**Issue by macscripter** [benwinding/react-admin-firebase#13]
Hi, 
May I suggest to modify this function adding return `Promise.reject();` ?
Reasons: the authentication is working perfectly agains firebase. However, no resource is protected once you're not logged in and try to access.... So `Promise.reject()` makes sense once the user is logged off and tries to access to a resource....

`  async HandleAuthCheck(params) {
    try {
      const user = await this.getUserLogin();
      log("HandleAuthCheck: user is still logged in", { user });
    } catch (e) {
      log("HandleAuthCheck: ", { e });
     return Promise.reject();
    }
  }`

**Comment by benwinding** [comment]
Thanks for bringing this to my attention @macscripter, 
The change (94d32631744b08311e88d35ebd98b1c78e2630b8) is included as version `0.5.1` which is now live, let me know if there are any issues.
Cheers,
Ben
