### ISSUE TITLE
Firestore and object reference

### ISSUE THREAD

**Issue by slecoustre** [benwinding/react-admin-firebase#131]
In my collection, my objects do contain an object reference table.

So when I want to display the list, I get a "parseAllDatesDoc" error. I can't understand why? and I can't figure out how to override it.

Can you help me?

Thank

**Comment by benwinding** [comment]
Hi @slecoustre,
Sorry, Firestore documents with field's of type `DocumentReference`  are currently not supported.
They should be supported when this Pull Request #127 is merged
Also related: #123
Cheers,
Ben

**Comment by slecoustre** [comment]
Hi @benwinding 
Thank you for your response, I saw after I made my request.

When do you think it'll be merge

**Comment by benwinding** [comment]
> When do you think it'll be merge

Hopefully the within the next week :+1:

**Comment by slecoustre** [comment]
Good 👌

**Comment by benwinding** [comment]
> Hopefully the within the next week 👍

Took longer than a week, but it's done now. Fixed by PR #127
