### ISSUE TITLE
Use this extension to login and upload files, not for data

### ISSUE THREAD

**Issue by MichalKalita** [benwinding/react-admin-firebase#135]
Hi, I have other react-admin-data extension for data.

I just want to use firebase auth login and firebase storage for images.

What is the best solution how to do it?

**Comment by benwinding** [comment]
Hi @MichalKalita, 

This library `react-admin-firebase` offers 2 providers:

1. **_DataProvider_** - Uses the Firestore Database + Firebase Cloud Storage
2. **_AuthProvider_** - Uses Firebase Authentication

You can configure one or both of them with `react-admin`.

## Uploading Files

Unfortunately, there's no way to use Firebase storage without Firestore, as the references to the Storage locations are stored within the Firestore database.

The path of the file is related to the document that you added for example:

| Firestore Document | File Field (source) | Stored File                                             |
|--------------------|---------------------|---------------------------------------------------------|
| /posts/1234567     | image_file          | gs://comm-unstable.appspot.com/posts/1234567/image_file |

Let me know if there's any issues/questions.

Cheers,
Ben

**Comment by benwinding** [comment]
Also see this StackOverflow answer which shows how to use multiple dataproviders in react-admin:

https://stackoverflow.com/questions/52889909/how-is-the-correct-way-to-have-multiple-dataproviders-in-react-admin
