### ISSUE TITLE
Missing or insufficient permissions.

### ISSUE THREAD

**Issue by thuan1412** [benwinding/react-admin-firebase#138]
I get the error "FirebaseError: [code=permission-denied]: Missing or insufficient permissions."  when my database rule is "allow read, write: if request.auth != null;"
With "allow read, write:" rule, everything works fine.

**Comment by benwinding** [comment]
@thuan1412, do you have the login page included? 

See here for more details: https://github.com/benwinding/react-admin-firebase/blob/master/src-demo/src/CustomForgotPassword.js

`allow read, write: if request.auth != null;` this means you need to be authenticated.

**Comment by thuan1412** [comment]
> @thuan1412, do you have the login page included?
> 
> See here for more details: https://github.com/benwinding/react-admin-firebase/blob/master/src-demo/src/CustomForgotPassword.js
> 
> `allow read, write: if request.auth != null;` this means you need to be authenticated.

Thank you, I solved the problem.

**Comment by gpietro** [comment]
@benwinding what do you mean by login page included?
I setup the admin with the default login page and it works if in firebase I have no restrictions but when I set `allow read, write: if request.auth != null;` I get the same error.
Is the access required before the user login? how to solve this? why do you point to a customforgotpassword page?
Thanks
