### ISSUE TITLE
Getting list of resource with rules associated to the user id will throw permission denied, even if querying by it

### ISSUE THREAD

**Issue by sebitoelcheater** [benwinding/react-admin-firebase#141]
Let's say there is a collection called `invoices` with an `uid` field that defines the user that owns an `invoice`.
Let's say there is a Firestore rule in order to protect `invoices` reading from users that do not own the `invoice`.
```
rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {
    match /invoices/{invoiceId} {
      allow read: if resource.data.uid == request.auth.uid;
    }
}
```
Then, the query
```
db.collection("invoices").where("uid", "==", firebase.auth().currentUser.uid).get()
```
will return the `invoices` owned by the current user, and will throw no error, as [documented here](https://firebase.google.com/docs/firestore/security/rules-query#secure_and_query_documents_based_on_a_field).
But calling
```
dataProvider.getList('invoices', {
        filter: {uid: userId},
        pagination: {page: 1, perPage: 60},
        sort: {field: 'uid', order: 1}
      })
        .then(({total, data}) => {
          setInvoices(data);
        })
        .catch(() => setInvoices(null))
```
Will log the user out.

**Comment by benwinding** [comment]
Hi @sebitoelcheater, Apologies for the delayed response. 

This is actually a limitation of the firestore security rules. There's a few points to remember when implementing rules like this:

Basically if you are checking the document's data field's in a Firestore rule then:
- Getting a single document will evaluate the rules ✓
- Getting a multiple documents (whole collections, partial collections) will not evaluate the rules and fail ✓

Basically if you're checking the document's `data()`, then firestore will return _all or nothing_.  

Please see the following resources which explain it in more detail:

- [Rules are not filters (official docs)](https://firebase.google.com/docs/firestore/security/rules-query#rules_are_not_filters)
- [What does it mean that “Firestore security rules are not filters”? (medium article)](https://medium.com/firebase-developers/what-does-it-mean-that-firestore-security-rules-are-not-filters-68ec14f3d003)

Cheers,
Ben
