### ISSUE TITLE
ReferenceError: localStorage is not defined

### ISSUE THREAD

**Issue by terrierscript** [benwinding/react-admin-firebase#142]
I use  `react-admin-firebase` with next.js, I got `ReferenceError: localStorage is not defined`.
It's seems occure from [Logger](https://github.com/benwinding/react-admin-firebase/blob/6e19e10846911b0ff82820cf44bcb20dfa5d7574/src/misc/logger.ts) and I try `{logging:false}` but this error occured.
Can I resolve this?

**Comment by benwinding** [comment]
Hi @terrierscript,
Yes `localStorage` is a browser side feature, used in both `react-admin-firebase` and `firebase`. Which means you cannot do server-side rendering with this library. 
I'm not sure how to do it, but you have to tell `next.js` not leave that part to the client SSR.
Let me know if this makes sense,
Cheers,
Ben

**Comment by terrierscript** [comment]
OK, I found  workaround

```js
import dynamic from "next/dynamic"

const DynamicComponent = dynamic(
  () => import("../compnent/MyAdminApp"),
  { ssr: false }
)

export default function Page() {
  return <DynamicComponent />
}
```

**Comment by oliverox** [comment]
Hi! Can we please reopen this issue. The workaround works during development, but when trying to build for production, the error: `ReferenceError: localStorage is not defined` appears again.

**Comment by oliverox** [comment]
Actually i am wrong... the workaround fixes it well. Thank you.
