### ISSUE TITLE
Can i disable  devtool console logs of react-admin-firebase. 

### ISSUE THREAD

**Issue by Gurdeep-Sharma** [benwinding/react-admin-firebase#145]

**Comment by Gurdeep-Sharma** [comment]
Hi ,
I want to disable react-admin-firebase console logs in build of my react app , can i do this ?

**Comment by benwinding** [comment]
Hey @Gurdeep-Sharma,
Sure, just use  
``` js
const options = { logging: false };
const dataProvider = FirebaseDataProvider(config, options);
```
Find more options here: https://github.com/benwinding/react-admin-firebase#options
Cheers,
Ben

**Comment by Gurdeep-Sharma** [comment]
Hey @benwinding ,
Thanks for the answer.
