### ISSUE TITLE
Server side filtering not supported in GET_MANY and GET_MANY_REFERENCE

### ISSUE THREAD

**Issue by amilgeorge** [benwinding/react-admin-firebase#148]
Server side filtering (using collectionQuery) is only supported  for GET_LIST queries. 
It will be nice to have server side filtering for GET_MANY and GET_MANY_REFERECE queries.

**Comment by benwinding** [comment]
Hi @amilgeorge,
This is now implemented in `GET_MANY_REFERENCE` queries. `GET_MANY` is not implemented though as it doesn't have a filter.
