### ISSUE TITLE
warning thrown by webpack due to incorrect firebase imports

### ISSUE THREAD

**Issue by monkeydri** [benwinding/react-admin-firebase#15]
Using CRA v2 and webpack 4 warnings are generated on startup :

```
It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');

ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

Typescript:
import * as firebase from 'firebase/app';
import 'firebase/<PACKAGE>';
```

This is because of the way Firebase is imported in [firebaseAuthProvider.ts](https://github.com/benwinding/react-admin-firebase/blob/94d32631744b08311e88d35ebd98b1c78e2630b8/src/firebaseAuthProvider.ts#L1) and [firebaseDataProvider](https://github.com/benwinding/react-admin-firebase/blob/94d32631744b08311e88d35ebd98b1c78e2630b8/src/firebaseDataProvider.ts#L1) : it should be `import * as firebase from "firebase/app";` instead of  `import * as firebase from "firebase";`.

see issue https://github.com/firebase/firebase-js-sdk/issues/848

**Comment by benwinding** [comment]
Thanks for reporting the issue, yes this is now fixed using the correct imports: 

Commit: 6654e8a2612212589ad914834aff50a3f3bd84ab

`import * as firebase from "firebase/app";`

It's deployed as version `0.5.2`. Let me know if there's any other issues or requests

Cheers,
Ben
