### ISSUE TITLE
productがhtmlそのまま出力されている

### ISSUE THREAD

**Issue by keisukee** [benwinding/react-admin-firebase#151]
![image](https://user-images.githubusercontent.com/38725877/95073227-6f852000-0747-11eb-8336-bee6f8f43d91.png)

**Comment by benwinding** [comment]
Hi @keisukee, 
If you're displaying HTML then you need the `<RichTextField />`
[As Shown in the React Admin Docs](https://marmelab.com/react-admin/Fields.html#richtextfield)
