### ISSUE TITLE
admin 親カテゴリを消す

### ISSUE THREAD

**Issue by keisukee** [benwinding/react-admin-firebase#152]
![image](https://user-images.githubusercontent.com/38725877/95073667-326d5d80-0748-11eb-820a-3e95426a5267.png)

親カテゴリが、一旦保存されると、消せない

**Comment by benwinding** [comment]
_From Google Translate:_
> Once the parent category is saved, it cannot be erased
Not sure what you mean by this? Can you give some more information?
