### ISSUE TITLE
Get photo url from storage

### ISSUE THREAD

**Issue by juhorichard** [benwinding/react-admin-firebase#153]
How I can get photo URLs from firebase storage with react-admin-firebase

Example:
 const photo = await firebase
    .storage()
    .ref("assets/photo.png")
    .getDownloadURL();

**Comment by benwinding** [comment]
Hi @juhorichard,

Apologies for the delay, you can now access the initialized firebase sdk app from the `dataProvider.app()`.

Your example would look like this:
``` js
const dataProvider = FirebaseDataProvider(config);
const photo = await dataProvider
  .app()
  .storage()
  .ref("assets/photo.png")
  .getDownloadURL();
``` 
Cheers,
Ben
