### ISSUE TITLE
How to get First & Last name  from email&password createAccount

### ISSUE THREAD

**Issue by splex7** [benwinding/react-admin-firebase#154]
![image](https://user-images.githubusercontent.com/12082436/95164713-75c9d980-07e5-11eb-9856-3d712037b0b2.png)

Hi! react-admin-firebase is awesome !! 
I got small question. I created firebase-function for create custom user profile to firestore.
 
When user submit createaccount form, functions.auth.user().onCreate(userRecord) triggered.
at that time, "userRecord" object contained email value but not displayName.
However, even though I entered First & Last name,  "displayName" is always null. 

I'd like to use the name user enter when they create account.
This is not very serious problem but Thanks for your concern~.
This is what i 've return from "userRecord" object.
```
{
  "uid": "UcKJjnUYPmMWmacukbQTqZtSa4j2",
  "email": "awesome@email.com",
  "emailVerified": false,
  "displayName": null,  //  **I expected the value what i've typed in "First & last name" form**
  "photoURL": null,
  "phoneNumber": null,
  "disabled": false,
  "passwordHash": null,
  "passwordSalt": null,
  "tokensValidAfterTime": null,
  "metadata": {
    "creationTime": "2020-10-06T05:48:14Z",
    "lastSignInTime": "2020-10-06T05:48:14Z"
  },
  "customClaims": {},
  "providerData": [
    {
      "email": "awesome@email.com",
      "providerId": "password",
      "uid": "awesome@email.com"
    }
  ]
}
```

**Comment by benwinding** [comment]
Not sure how to edit that field, you might be able to edit the fields after the user has _Signed Up_ and has been created.

Aparently you can edit the fields once the user has logged in, as this SO answer shows:

https://stackoverflow.com/a/38389406/2419584

Anyway this isn't really related to this repository, so I'm closing the issue for now.
