### ISSUE TITLE
Cannot update/delete anything

### ISSUE THREAD

**Issue by Will-Mann-16** [benwinding/react-admin-firebase#157]
I've set this up with React Admin for my data in firestore, but I can't seem to update or delete anything? I can create new entries but nothing else. Anyone have any ideas why? I'm running my own custom authentication in the root level app, and disabled the provider for the main react admin.

It's on a pastebin because github was being a pain in formatting it correctly.

https://pastebin.com/7nka87bm

**Comment by benwinding** [comment]
Apologies for the delay, if you haven't already solved it. Try the following:

- Do you have rules on your firestore database? That could be a reason there's nothing updated/deleted.
- Can you update to the latest version (deployed `3.2.10` today)

Let me know how you go,
Cheers,
Ben
