### ISSUE TITLE
Filter by array-contains

### ISSUE THREAD

**Issue by steventilator** [benwinding/react-admin-firebase#158]
Is it possible to add a permanent filter to query with `array-contains`? Like `firebase.firestore().collection('users').where('companies', 'array-contains', companyID)` but with the `filter` property on a `List` component.

**Comment by steventilator** [comment]
Sorry, my mistake. `filter={{ companies: company.id }}` works if `company.id` isn't `undefined`...

**Comment by benwinding** [comment]
Hi @steventilator,
Yes it is possible to pass any firebase query into the filter by passing in a `collectionQuery` function.

Your's would look something like this:
``` js
<List
  {...props}
  filter={{
    collectionQuery: (collection) => collection.where('companies', 'array-contains', companyID),
  }}
>
``` 
Let me know if you have any more difficulties,
Cheers,
Ben
