### ISSUE TITLE
Login on react admin only if user have some custom claim

### ISSUE THREAD

**Issue by CBrian04** [benwinding/react-admin-firebase#160]
Hi Benwinding, and before telling you about my problem, I would like to thank you a lot for your wonderful work on this project!
I build an e-commerce app where I included react-admin to handle changes in product's database made by the owner of the business.
Problem is that I don't know if there is a way to pass an option to the AuthProvider to login users only if they have a particular firebase custom claim (admin for example). For the while, based on your code I guess that you just use custom claims for allowing some type of users to write in database, and some others not (and by the way hide some parts to some users). I think that in the case of react admin included in another app, it would be a good idea to implement it because you already have some customer users which obviously would not be able to login on react admin.

**Comment by benwinding** [comment]
Hi @CBrian04,
Thanks for checking out the project. You would need to do 2 things:
- Wrap the default Auth Provider in order to check custom claims first [see this link for details](https://github.com/marmelab/react-admin/blob/master/docs/Authorization.md)
- Check custom claims using the _react-admin-firebase_ auth provider [as shown here](https://github.com/benwinding/react-admin-firebase/issues/120#issuecomment-631166684)

I will update the documentation in the future to make this more clear.
Cheers,
Ben

**Comment by CBrian04** [comment]
Thanks a lot for the response, I have done something like the code below to modify the handlelogin function before you answered me ( I put it here if someone is interested), it seems to work quite well, I will take a look at the resource you gave me to see if I can improve my code.

My code : 

`const authProviderF = FirebaseAuthProvider(config, options);
const handlelogin = async (params) => {
  const { username, password } = params;

  if (username && password) {
    try {
      const user = await firebase.auth().signInWithEmailAndPassword(
        username,
        password
      );
      
      const tokenResult = await firebase.auth().currentUser.getIdTokenResult();
      if(tokenResult.claims.admin !== true) {
        firebase.auth().signOut();
        throw new Error("You don't have permission to enter here!")
      } else {
        console.log("HandleAuthLogin: user sucessfully logged in", { user });
        return user;
      } 
    } catch (e) {
      console.log("HandleAuthLogin: invalid credentials", { params });
      throw new Error("Error: bad credentials");
    }
  } else {
    return this.getUserLogin();
  }
}
const authProvider = {
  ...authProviderF,
  login: params => handlelogin(params)
}`

**Comment by benwinding** [comment]
Glad you got it working @CBrian04!

- Here's another example of _Authorization_: https://github.com/benwinding/react-admin-firebase/issues/69#issuecomment-657919226

## Another Way
The following is a pretty clean way to wrap the _AuthProvider_ (should have linked this before!)

``` ts
const authProvider = FirebaseAuthProvider(firebaseConfig, options);
const dataProvider = FirebaseDataProvider(firebaseConfig, options);

// Use this just like the normal auth provider
const myAuthProvider = {
  // Copy all authprovider functionality
  ...authProvider,
  // Wrap the login and check for custom claims
  login: async (params) => {
    const user = await authProvider.login(params);
    // getPermissions is how when get the custom claims for the logged in user
    const claims = await authProvider.getPermissions();
    const isAdmin = Array.isArray(claims) && claims.includes("admin");
    if (isAdmin) {
      return user;
    }
    // Make sure user is logged out, if not an admin
    await authProvider.logout()
    throw new Error("Login error, invalid permissions");
  },
};
```
Cheers,
Ben
