### ISSUE TITLE
Filtering with gte/lte

### ISSUE THREAD

**Issue by s-graber** [benwinding/react-admin-firebase#161]
I'm trying to use filters such as
`<DateInput source="date_gte" />`
But I don't find this type of filtering feature in the provider.
How can I achieve this way of filtering?

**Comment by benwinding** [comment]
Hi @s-graber,
We've just updated the DataProvider to the new _react-admin 3.x_ api. Would you be able to check the issue still exists. Few other things you can do: 
- How to use the DataProvider to filter items:
https://marmelab.com/react-admin/DataProviders.html 
- Check the tests in this repo to see how the filter works ([example test](https://github.com/benwinding/react-admin-firebase/blob/master/tests/integration-tests/ApiGetList.spec.ts))

Cheers,
Ben

**Comment by s-graber** [comment]
Hi @benwinding,
it still exists. I checked with the a test in ApiGetList.spec.ts:

```javascript
test("FirebaseClient with filter gte", async () => {
    const testDocs = [
      {
        title: "A",
        volume: 100,
      },
      {
        title: "B",
        volume: 101,
      },
      {
        title: "C",
        volume: 99,
      }
    ];
    const collName = "list-filtered";
    const collection = fire.db().collection(collName);
    await Promise.all(testDocs.map((doc) => collection.add(doc)));

    const client = new FirebaseClient(fire, {});
    const result = await client.apiGetList(collName, {
      filter: {
        volume_gte: 100
      },
      pagination: {
        page: 1,
        perPage: 10,
      },
      sort: {
        field: "obj.volume",
        order: "ASC",
      },
    });
    const third = result.data.length as any;
    expect(third).toBe(2);
  }, 100000);
```

I tried to use collectionQuery but I didn't get it run for dynamic filtering.

**Comment by benwinding** [comment]
Hi @s-graber ,

A couple of points:

- That sort field is incorrect changed data to have `obj` field too
- There's no way to query like that in the `react-admin` base framework
- You need to use the `collectionQuery` interface in the filter (as shown below in the working test).
- Not sure how you can get dynamic filtering with `collectionQuery` interface though, but I'm sure it's possible as that `collectionQuery` function is called everytime data is fetched by the underlying framework

``` typescript
  test("FirebaseClient with filter gte", async () => {
    const testDocs = [
      {
        title: "A",
        obj: {volume: 100},
      },
      {
        title: "B",
        obj: {volume: 101},
      },
      {
        title: "C",
        obj: {volume: 99},
      }
    ];
    const collName = "list-filtered";
    const collection = fire.db().collection(collName);
    await Promise.all(testDocs.map((doc) => collection.add(doc)));

    const client = new FirebaseClient(fire, {});
    const result = await client.apiGetList(collName, {
      filter: {
        collectionQuery: (c: firebase.firestore.CollectionReference) => c.where('obj.volume', '>=', 100) 
      },
      pagination: {
        page: 1,
        perPage: 10,
      },
      sort: {
        field: "obj.volume",
        order: "ASC",
      },
    });
    const third = result.data.length as any;
    expect(third).toBe(2);
  }, 100000);
```

Let me know how you go
