### ISSUE TITLE
Signup a user on Firebase Authentication

### ISSUE THREAD

**Issue by tux240** [benwinding/react-admin-firebase#162]
hi,

Is it possible to signup a new user when creating a new user in the admin list ?
Or, is it possible to call a Firebase Cloud Function ?

Thanks

**Comment by benwinding** [comment]
Hi @tux240,

If you'd like to allow signups on the site you can use the [CustomLoginPage described here](https://github.com/benwinding/react-admin-firebase/blob/663dad9b71dde6dc999710eec69d563a3f08093a/src-demo/src/CustomLoginPage.js): 

If you'd like to create a user, _AFTER_ adding them in a firestore collection (users). Then you might want to create a cloud function which watches that collection ([see this link](https://firebase.google.com/docs/functions/firestore-events#writing-triggered_functions))

**Comment by michalens** [comment]
@benwinding how do I then set up a password for that user? Is there a way for email to be sent to the user, with a link where he can set up his password.
Also, how to reset passwords?

**Comment by benwinding** [comment]
Hi @michalens,
That's out of the scope of this package for now. Please check out the Firebase documention:
https://firebase.google.com/docs/auth/admin/email-action-links#generate_password_reset_email_link 
I would recommend making a cloud function that emails someone a firebase generated password reset link.
Cheers,
Ben
