### ISSUE TITLE
Sort not working when key is nested like "key.subKey"

### ISSUE THREAD

**Issue by sreenath-n** [benwinding/react-admin-firebase#163]
![image](https://user-images.githubusercontent.com/69649218/98504288-9ec60a00-227c-11eb-97fa-6bc01da46ae2.png)

The following TextField tag is used:

`<TextField source="totalValue.totalEstimatedAmount" label="Total Amount" />`

Sort is not working in this case. Any workaround for now ?

**Comment by benwinding** [comment]
Hey @sreenath-n, 
Should be fixed in `react-admin-firebase@3.2.7`, 
Let me know if that works now.
Cheers,
Ben

**Comment by sreenath-n** [comment]
This is working correctly now.
Thanks @benwinding
