### ISSUE TITLE
DateField incorrectly shows hour as 0 for AM/PM format

### ISSUE THREAD

**Issue by sreenath-n** [benwinding/react-admin-firebase#164]
![image](https://user-images.githubusercontent.com/69649218/98505063-61fb1280-227e-11eb-9ba3-495d30d084e5.png)

The following DateField tag is used:

`<DateField showTime options={{ weekday: 'short', month: 'short', day: 'numeric', hour: 'numeric', minute: '2-digit', hour12: true }} />`

**Comment by benwinding** [comment]
Hi @sreenath-n 
That's strange! Yeah the `<DateField />` is actually a part of the [react-admin](https://marmelab.com/react-admin/Fields.html#datefield) library. 
Please create an issue in that repository: https://github.com/marmelab/react-admin/issues
Cheers,
Ben

**Comment by sreenath-n** [comment]
Thanks @benwinding 
I just created the issue in react-admin:
https://github.com/marmelab/react-admin/issues/5507
