### ISSUE TITLE
apiUpdate has no await, apiUpdateMany does. Expected ?

### ISSUE THREAD

**Issue by pasdoy** [benwinding/react-admin-firebase#168]
apiUpdate https://github.com/benwinding/react-admin-firebase/blob/master/src/providers/database/FirebaseClient.ts#L156

apiUpdateMany https://github.com/benwinding/react-admin-firebase/blob/master/src/providers/database/FirebaseClient.ts#L184

I ran into a issue where I use a externally provided composent (it uses firebase client directly). The react-admin Edit (undoable=false) component redirect to that page. Both use the same collection. Sometimes after a edit the values read by the external component weren't updated (reading before the updated data reached firebase after the redirect on edit). Adding await to apiUpdate fixed it. 

Is it expected that there's no await ? Should I do things differently ?

**Comment by benwinding** [comment]
Hi @pasdoy, 
That I think it was to provide a faster experience for people (as it would return immediately) but this seems like a stupid idea now...
Converted it back, should be deployed in version `3.2.11`.
Cheers,
Ben
