### ISSUE TITLE
FirebaseAuthProvider - method to identify active user details - UID, Email, etc

### ISSUE THREAD

**Issue by tfesslerCWC** [benwinding/react-admin-firebase#17]
How does one find identify the current user logged in through the FirebaseAuthProvider Login?   Hopefully there is an easy way to access this object to obtain the current users uid and email that can be added to a new record as its created.

**Comment by benwinding** [comment]
Hey @tfesslerCWC,
That's a great idea, I just updated the package to version `0.5.6` which allows this functionality.
To get the currently logged in user run:

``` js
const user = await authProvider('AUTH_GETCURRENT')
```

This will return the Firebase user object, or null if there is no currently logged in user.
Thanks,
Ben
