### ISSUE TITLE
Question: Use filters to set filter prop?

### ISSUE THREAD

**Issue by steventilator** [benwinding/react-admin-firebase#173]
If I'm not mistaken, setting default filters with the `filter` prop (not `filters`) is a way to reduce the number of documents the `List` component fetches from Firestore. Instead of fetching the complete collection and filter on device, the `List` then only fetches the documents that pass the `filter` query.

Is there a way to use the react-admin `filters` to set the `filter` prop?

For example, if I have the filter component like this:

```
const SessionFilter = props => {
  return (
    <Filter {...props}>
      <NullableBooleanInput
        source="isReviewed"
        alwaysOn
      />
      <ReferenceInput
        source="employee"
        reference="employees"
        alwaysOn
      >
        <AutocompleteInput optionText="fullName" />
      </ReferenceInput>
    </Filter>
  );
};
```

...and pass it to a List like this:

```
<List
  {...props}
  filters={<SessionFilter />}
>
    {content}
</List>
```
...it would automatically set the `filter` of the List:

```
  <List
      {...props}
      filters={<SessionFilter />}
      filter={{ field: filter }} // This would be dynamically created based on the SessionFilter component.
    >
    {content}
</List>
```

**Comment by benwinding** [comment]
Hey @steventilator,
[According to the documentation](https://marmelab.com/react-admin/List.html#filters-filter-inputs) the `filter` prop is for permanent filter attributes, meaning you can't dynamically alter it, but I'm not 100% sure. Maybe try asking the question on the `react-admin` project and let me know how you go.
Unless anyone else has anymore information?
Cheers,
Ben

**Comment by bayareacoder** [comment]
You can use the `setFilters` callback from your custom filter component to set `filter` manually See https://marmelab.com/react-admin/List.html#building-a-custom-filter

PS
The more efficient approach with Firebase for filtering is to structure your data such that whatever you need to filter on is part of the path that you subscribe to.

**Comment by steventilator** [comment]
@bayareacoder Thanks for the tip. That would actually work. Unfortunately, I need to set the `collectionQuery` key in the `filter` object. My task is to query by a date range. (In my case, show all sessions in a month.)

@benwinding Asking in the `react-admin` project was not helpful: https://github.com/marmelab/react-admin/issues/5586

I ended up solving it with the use of a Cloud Function.

**Comment by benwinding** [comment]
@steventilator, sorry to hear that it wasn't helpful, yeah I guess StackOverflow is a better place to post. 

But glad to hear you fixed the issue.

**Comment by rahulserver** [comment]
@steventilator can you detail how you solved this issue? I too need to filter by date range(I assume one of the biggest issues people are stuck with while using this module).
