### ISSUE TITLE
How do you override some of the default fields that are sent to cloud firestore?

### ISSUE THREAD

**Issue by gyatashoa** [benwinding/react-admin-firebase#174]
I wanted know how to override certain fields that are sent to cloud firestroe with a different title,
Like the createdate field, i wanted to make it created_at

**Comment by benwinding** [comment]
Hi @gyatashoa,
This was originally too hard to implement, but after a good refactor it was easy. So there's a new option you can use called `renameMetaFields`, it's used like this below:
``` ts
const options = {
  // Have custom metadata field names instead of: 'createdate', 'lastupdate', 'createdby', 'updatedby'
  renameMetaFields: {
    created_at: 'my_created_at', // default: 'createdate'
    created_by: 'my_created_by', // default: 'createdby'
    updated_at: 'my_updated_at', // default: 'lastupdate'
    updated_by: 'my_updated_by', // default: 'updatedby'
  },
}
``` 
Let me know if there's any issues,
Cheers,
Ben
