### ISSUE TITLE
Accessing the "type" in "rawFile" from FileInput

### ISSUE THREAD

**Issue by RyanDingo** [benwinding/react-admin-firebase#176]
Does anyone know how to check the file type of the rawFile that gets created through FileInput? 

I have tried a number of ways, record.rawFile gets me to the File but then I get stuck when it comes to getting to the type. I can't do record.rawFile.type. does anyone have any ideas? 

I would greatly appreciate it.

**Comment by benwinding** [comment]
Rawfile is just a temporary field that is removed after the file is uploaded to cloud storage.

If you just want to allow certain files you can use the `accept` field in the `<FileInput />` component [as shown here](https://marmelab.com/react-admin/Inputs.html#fileinput).

``` jsx
<FileInput accept="application/json,video/*" />
```

**Comment by RyanDingo** [comment]
Thank you Ben! I am not sure how I passed by that so many times in the documentation.
