### ISSUE TITLE
Typings not found

### ISSUE THREAD

**Issue by RWOverdijk** [benwinding/react-admin-firebase#18]
I have the same issue with react-admin so perhaps it's just something I missed but, simply running init steps and then importing ta-firebase in App.tsx gives me:

```
TS7016: Could not find a declaration file for module 'react-admin-firebase'. 

'/Users/rwoverdijk/projects/site/bluetour-admin/node_modules/react-admin-firebase/dist/index.js' implicitly has an 'any' type. 
  Try `npm install @types/react-admin-firebase` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-admin-firebase';`
```

To reproduce:

1. yarn create react-app my-app --typescript
2. yarn add react-admin
3. Open App.tsx and import react-admin-firebase
4. _above ts error'._

**Comment by benwinding** [comment]
Thanks for checking out the project!

Yes `react-admin` has the known issue of having _no_ types for typescript integration ([see this issue](https://github.com/marmelab/react-admin/issues/250)). 

However this project was written in typescript, so I've added the typings to the npm package too, in `react-admin-firebase` version `0.5.5`.

Checkout this demo project I've just released using: https://github.com/benwinding/react-admin-firebase-demo-typescript

Cheers,
Ben

**Comment by RWOverdijk** [comment]
Hmmm no that's not working for me. Still getting 

```
TS7016: Could not find a declaration file for module 'react-admin-firebase'. '/....../node_modules/react-admin-firebase/dist/index.js' implicitly has an 'any' type.
```

**Comment by benwinding** [comment]
Dang! Sorry to hear that.

I just repeated you're setup and it worked for me, can you confirm if the following works:

1. `yarn create react-app my-app --typescript`
2. `yarn add react-admin`
3. Add `import { FirebaseDataProvider } from "react-admin-firebase";` to the App.tsx
4. `yarn start`

This should compile the project using the types found in the `react-admin-firebase` npm package, which are found in the [package.json file in react-admin-firebase](https://github.com/benwinding/react-admin-firebase/blob/1a007ecf05da69c84cd700a4f6bcae4517bc5f41/package.json#L34).

My system is using:
- npm 6.4.1
- node v8.15.0
- typescript 3.4.5

Let me know if this works out for you.

Cheers,
Ben

**Comment by RWOverdijk** [comment]
I think it's missing a step, you're not installing react-admin-firebase.

But I see you're [being a ninja again](https://github.com/benwinding/react-admin-firebase/commit/5310277b9357234f2424139df9e718d250480e52) which is cool. I like ninjas. Nice fix, thanks!
