### ISSUE TITLE
Hiding resource based on permissions doesn't remove it from Sidebar

### ISSUE THREAD

**Issue by gessic-apps** [benwinding/react-admin-firebase#182]
Hi,

I'm using permissions as stated in #140   so that resources are hidden based on custom claims. Although this results in unauthorized users getting an error page "Either you typed a wrong URL, or you followed a bad link.." , it still appears as a clickable link in the side bar:

```
<Admin dashboard={Dashboard}  layout={MyLayout} loginPage={CustomLoginPage} authProvider={myAuthProvider} dataProvider={dataProvider} >
        {permissions => [ 
        permissions === 'Admin' && <Resource name="incidents" list={   IncidentList  }  edit={IncidentEdit} />   ,
        permissions === 'Admin' && <Resource name="surveys" list={   SurveyList  }  edit={SurveyEdit} create={SurveyCreate} /> 
        ]}
      </Admin>
```

And here's the what it looks like (it works fine for actual admin users).:

<img width="1339" alt="image" src="https://user-images.githubusercontent.com/59149159/109392508-5f363300-78ea-11eb-83d3-d73c70cd3d5e.png">

My question is: how do I actually hide the resource link , not just have it redirect to an error page?

**Comment by DanielSanchez94** [comment]
Hi, LET US KNOW IF I FOUND ANY SOLUTION. I HAVE THE SAME PROBLEM

REGARDS

**Comment by benwinding** [comment]
Hi Guys,

This is a behavior of the default menu component for `react-admin`. And doesn't seem to change dynamically based on adding/removing resources with permissions for some reason.

If you'd like to hide the menu item for a resource you'll need to create a **custom menu** component and pass that into a **custom layout** component and pass that to the react-admin app instance. More details on how to do that here:

https://marmelab.com/react-admin/Theming.html#using-a-custom-menu

I'll close this out for now, as it seems to be a `react-admin` issue, but let me know how you go.

Cheers,
Ben
