### ISSUE TITLE
How to add doc ID as a field?

### ISSUE THREAD

**Issue by kiptoomm** [benwinding/react-admin-firebase#189]
Good day @benwinding, 

I was looking at the [options docs](https://github.com/benwinding/react-admin-firebase#options) and it looks to me that I should be able to add an 'id' field matching a document's ID to its record. That is, with:

`dontAddIdFieldToDoc: false`

The current situation: 
![Screen Shot 2021-04-28 at 12 19 29 AM](https://user-images.githubusercontent.com/1447912/116314156-6c22b600-a7b7-11eb-9f6e-8434b5f8c8a9.png)

I believe I should have a key-value pair that looks like this: `{ ..., id: xL89z8ek1hyAhJLLNulW, ...}`

I have also tried setting the value of this option to `true` but in neither case does the desired field get created. What should I do to make sure the 'id' field is present in all my documents?

**Comment by benwinding** [comment]
Hi @kiptoomm ,
Thanks for reporting the issue, yes that field wasn't being added automatically only removed. 
Should be fixed in version `react-admin-firebase@3.2.18`
Cheers,
Ben
