### ISSUE TITLE
Update to firebase 8

### ISSUE THREAD

**Issue by AustenLamacraft** [benwinding/react-admin-firebase#191]
[firebase-web-react](https://github.com/firebase/firebaseui-web-react) recently updated to firebase 8. It seems the only breaking change is [this one](https://firebase.google.com/support/release-notes/js#version_800_-_october_26_2020) i.e. to use the default import 

`import firebase from 'firebase/app'`

It looks like this should work out of the box, though I haven't tested it

**Comment by benwinding** [comment]
This is related to issue #202

`react-admin-firebase@3.2.30+` now supports `firebase@9+`
