### ISSUE TITLE
Doesn't work with Firebase@9.0.0-beta.7

### ISSUE THREAD

**Issue by Jerunnon** [benwinding/react-admin-firebase#202]
I get the following error with the new Firebase version: 

Could not resolve dependency:
peer firebase@"^7.9.x" from react-admin-firebase@3.2.24
node_modules/react-admin-firebase
  react-admin-firebase@"*" from the root project

Full error Report attached

[eresolve-report.txt](https://github.com/benwinding/react-admin-firebase/files/6973457/eresolve-report.txt)

**Comment by benwinding** [comment]
`react-admin-firebase@3.2.30+` now supports `firebase@9+`
