### ISSUE TITLE
Can we please get fix-123 to master

### ISSUE THREAD

**Issue by reijerteunis** [benwinding/react-admin-firebase#205]
Hi,

First of all thanks for this contribution. Really appreciate the whole project you have build.

For my case in order to user it I would really need the DocumentReference in this project. Therefor is there an option to release the fix-123 branch?

Thanks,

Ruud

**Comment by s-limo** [comment]
Maybe it is possible to disable Refence field parsing, or parsing at all? I get call stack error with lists containing reference fields
![image](https://user-images.githubusercontent.com/1849760/134895683-af378704-49c1-4f5d-88bf-38e1454bf131.png)
(unless this is different issue)

**Comment by benwinding** [comment]
Merged in by #127
