### ISSUE TITLE
Edit not working

### ISSUE THREAD

**Issue by RWOverdijk** [benwinding/react-admin-firebase#21]
> react-admin-firebase: No id found matching: some_id_here

When directly navigating to a specific id to edit, it's not found. I think this is due to how data is loaded.

**Comment by benwinding** [comment]
I'm unable to reproduce this, can you confirm this is still an issue and is broken for version `0.5.6`? Or create a basic github project to reproduce this?
Cheers,
Ben

**Comment by RWOverdijk** [comment]
I think it was an issue before I updated. Ninja fixes everywhere 😎
