### ISSUE TITLE
[feature-request] Get progress on file upload / document save

### ISSUE THREAD

**Issue by xididri** [benwinding/react-admin-firebase#214]
It would be nice to have a progress info updates for file upload and or document update. Here is my use case:

I have a document with a `file` field, I use a `FileInput` in react-admin to upload the actual file (uploaded to Firebase Storage).

The file upload happens hitting save. The UI then displays the document in "loading" state while data is actually uploaded (Save button is grayed out and progress bars are visible on the referenced fields).

When the upload is complete (on Firebase Storage), the document is then updated (let's say field `file` now contains `src: [ur](https://firebasestorage.googleapis.com/v0/b/...`) and the UI is now is "normal" state (all data is visible and Save is button active).

This is not very convenient when uploading large files because we don't really know if the upload has really started.

Apologies if this issue should be on [react-admin](https://github.com/marmelab/react-admin) but I have the feeling that react-admin has no way to get progress information from Firebase storage upload.

**Comment by benwinding** [comment]
Fixed by your contribution in PR #215 
Thanks 🙏
