### ISSUE TITLE
admin.isLoggedIn = false after logging in

### ISSUE THREAD

**Issue by RWOverdijk** [benwinding/react-admin-firebase#22]
I found that isLoggedIn is always set to false in redux. This means that when I try to use permissions in my <Admin /> declaration I always get sent to login.

**Comment by benwinding** [comment]
Just looking into this, it seems the AuthProvider is meant to set this not the `react-admin` framework, which is weird, oh well... [related issue](https://github.com/marmelab/react-admin/issues/1967)

How should this be implemented? How do I set `admin.isLoggedIn`, I can't find much documentation on `isLoggedIn` only [this line](https://github.com/marmelab/react-admin/blob/d04af4c28513846c1b557d8ad49fcb7496241c62/packages/ra-core/src/auth/WithPermissions.tsx#L9) in the `react-admin` source.

Any help pointing me in the right direction would be much appreciated!

**Comment by RWOverdijk** [comment]
By implementing the action I think. Might be related to this comment: https://github.com/benwinding/react-admin-firebase/issues/23#issuecomment-493767085

**Comment by tfesslerCWC** [comment]
From the firebase perspective.... [Custom claims ](https://firebase.google.com/docs/auth/admin/custom-claims)can be set on the user account when created.  When the user logs in, the custom claims of isAdmin:true could be evaluated for application rights.

Looking at several React-admin firebase/firestore examples, when configuring the AuthProvider, params are usually passed to identify a firebase DB object containing the user profile where isAdmin:true is stored.  Whereas when configuring the AuthProvider in this project only passes the firebase configuration.

**Comment by RWOverdijk** [comment]
@tfesslerCWC Claims work with functions or a server. It's nice, but does require more infra (unless they added a UI that I'm unaware of?).

**Comment by benwinding** [comment]
Hi @RWOverdijk and @tfesslerCWC,

Would you be able to confirm if this problem is fixed? As issue #23 has been fixed in version `0.6.5`.

Also, by getting the firebase User object from the `FirebaseAuthProvider`, via:

``` javascript
const user = authProvider('AUTH_GETCURRENT');
```

Then you can access the custom claims for the user. I'm pretty sure you can only _edit_ the claims with the `firebase-admin` npm package which is a server side package, but you could still use them, just like @RWOverdijk demonstrates in this comment: https://github.com/benwinding/react-admin-firebase/issues/23#issuecomment-493767085

Let me know how you go.

Cheers,
Ben

**Comment by RWOverdijk** [comment]
@benwinding This is currently not relevant for me as I'm just using firebase itself in my sagas. Time is a pita so maybe in the future 😄

**Comment by benwinding** [comment]
Ok no worries :smile:, 

FYI; if this helps, you can also pass a previously initialized firebase app instance into the providers now too:
``` javascript
// All options are optional
const options = {
  // Your own, previously initialized firebase app instance
  app: firebaseAppInstance;
}

const dataProvider = FirebaseDataProvider(config, options);
const authProvider = FirebaseAuthProvider(config, options);
```
I'll close this for now, and reopen it if the issue continues.
Cheers,
Ben
