### ISSUE TITLE
Documentation website is broken

### ISSUE THREAD

**Issue by mickael-h** [benwinding/react-admin-firebase#222]
https://benwinding.github.io/react-admin-firebase/
I just get a blank page and this error in the console:
![image](https://user-images.githubusercontent.com/7953005/155891963-4944b16f-508d-4993-980f-2b84db9cc771.png)

**Comment by benwinding** [comment]
Should be fixed now, it was a problem with parsing the JSON string here

https://github.com/benwinding/react-admin-firebase/blob/e14509396f794f43307a9de6d370205562c1a4fa/src-demo/src/App.js#L19
