### ISSUE TITLE
Pagination broken with Lazy Loading?

### ISSUE THREAD

**Issue by casconed** [benwinding/react-admin-firebase#226]
With lazy loading enabled, all of my large collections show that they have 9000 items, even when they definitely have fewer. It seems like the Provider here should be using [Partial Pagination](https://marmelab.com/react-admin/DataProviderWriting.html#partial-pagination) but maybe isn't?

![Pagination](https://user-images.githubusercontent.com/102230/164108117-1e6acaaa-0eae-429f-88da-fe93b038086a.png)

**Comment by casconed** [comment]
Closing because I see that it is hardcoded in the provider.

**Comment by benwinding** [comment]
Hi @casconed,
Thanks for checking out the library, yes this is a limitation with Firestore, as it doesn't allow us to check the total collection size without pulling **_every single document_**. [More context around this decision here](https://github.com/benwinding/react-admin-firebase/issues/59#issuecomment-644399949)
