### ISSUE TITLE
Custom Firebase/Firestore document name/key

### ISSUE THREAD

**Issue by tfesslerCWC** [benwinding/react-admin-firebase#24]
Currently, react-admin-firebase uses Firebase random generated ID's for all database entries.    For my users collection, I want to set the document ID from the params.email field.

firebaseDataProvider.TS currently uses 'collection.add()' for adding records.
For select cases it would be helpful to use  connection.doc(someVar).set(params.data)

`
   public async apiCreate(
    resourceName: string,
    params: IParamsCreate
  ): Promise<IResponseCreate> {
    const r = await this.tryGetResource(resourceName);
    log("apiCreate", { resourceName, resource: r, params });
    const doc = await r.collection.add({
      ...params.data,
      createdate: firebaseApp.firestore.FieldValue.serverTimestamp(),
      lastupdate: firebaseApp.firestore.FieldValue.serverTimestamp()
    });
    return {
      data: {
        ...params.data,
        id: doc.id
      }
    };
  }`

**Comment by benwinding** [comment]
Hi again @tfesslerCWC,
Apologies for the delay. So I've just made an easy fix for this to accomplish what you want. Just add the "id" field to the `Create` component in your app, then you can override the random firestore document id's. Example:

``` javascript
export const UserCreate = (props) => (
  <Create {...props} >
    <SimpleForm>
      <TextInput source="id" /> // Will be added to firestore using; doc(id).set(data)
      <TextInput source="name" />
      <TextInput source="age" />
    </SimpleForm>
  </Create>
);
```
This is implemented in version `0.6.4`. Let me know if this works for you.
Cheers,
Ben

**Comment by dhstack** [comment]
@benwinding For some reason the custom document id isn't working when using react-admin's `FormDataConsumer` to prepopulate the field based on other values entered into the form. It works as you describe with just a regular `TextInput` though.

Here's what I'm trying to do:

```
const initialValues = {
  programId: '',
  week: 1,
  day: 1,
  message: ''
};

const SmsCreate = props => {
  return (
    <Create successMessage="SMS message created!" {...props}>
      <SimpleForm initialValues={initialValues} redirect="list">
        <ReferenceInput
          label="Program"
          source="programId"
          reference="programs"
        >
          <SelectInput optionText="name" />
        </ReferenceInput>
        <NumberInput source="week" validate={minValue(1)} />
        <SelectInput source="day" choices={[
          { id: 1, name: '1' },
          { id: 2, name: '2' },
          { id: 3, name: '3' },
          { id: 4, name: '4' },
          { id: 5, name: '5' },
          { id: 6, name: '6' },
          { id: 7, name: '7' },
        ]} />
        <FormDataConsumer>
          {({ formData, ...rest }) =>
            <TextInput
            source="id"
            value={formData.programId + "_" + formData.week + "_" + formData.day}
            {...rest}
            />
          }
        </FormDataConsumer>
        <TextInput
            multiline
            fullWidth
            source="message"
            label="Message"
          />
      </SimpleForm>
    </Create>
  );
};
```

Basically, I want the document id to be programId, week, and day concatenated as the document id: `programId_week_day`

**Comment by dhstack** [comment]
Figured it out!

I needed to be using the `useForm` hook from `react-final-form` as [documented here](https://marmelab.com/react-admin/Inputs.html#linking-two-inputs), and `onChange` and `react-final-form`'s `getFieldState`. For example, this goes on the field that is updated:

```
onChange={value => form.change('id', form.getFieldState('programId').value + "_" + form.getFieldState('week').value + "_" + form.getFieldState('day').value)}
```
