### ISSUE TITLE
Unable to create post

### ISSUE THREAD

**Issue by shidevil** [benwinding/react-admin-firebase#258]
Hi everyone,

I just want to check so there seems to be an issue with the create post, and it can't be created. I have not touched any code yet. 

1. Git clone
2. Put in firebase config (check on rule)
3. yarn
4. yarn start-demo

I would appreciate any help! 

<img width="900" alt="Screenshot 2023-01-27 at 4 23 35 PM" src="https://user-images.githubusercontent.com/5009021/215041200-342b976b-fef0-4963-9004-1eef913b1113.png">

**Comment by shidevil** [comment]
Tested in the sample - https://benwinding.github.io/react-admin-firebase/

Did not work as well

**Comment by shidevil** [comment]
@Georgi-Slavchev did you managed to solve ur issue?

**Comment by Georgi-Slavchev** [comment]
Yes sorry, I was not very clear on that. Inside the ResourceManager.ts there are two functions: getCurrentUserEmail, getCurrentUserId. I replaced the if - else with try catch where in the catch I just return the logic from the else.

**Comment by shidevil** [comment]
could you share the code @Georgi-Slavchev and probably can do a pull request if it’s broken.

**Comment by KonkretneKosteczki** [comment]
I had the same issue and resolved it by simply filtering out the undefined fields. 

When you initialize the dataprovider you can pass the `transformToDB` option to it.

``` js
        import {FirebaseDataProvider} from "react-admin-firebase";

        const config = {
          apiKey: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
          authDomain: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
          databaseURL: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
          projectId: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
          storageBucket: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
          messagingSenderId: "aaaaaaaaaaaaaaaaaaaaaaaaaaa",
        };
        const dataProvider = FirebaseDataProvider(config, {
          app: firebaseAppInstance,
          transformToDb: (resourceName, documentData) => {
              // remove undefined fields from the document, since firestore does not accept undefined as a field value
              return Object.fromEntries(
                  Object.entries(documentData).filter(([, val]) => val !== undefined)
              );
          }
        });
 ```
 
 It's not a catch all clause because it would not remove undefineds for nested objects, but for your purpose it seems satisfactory.
