### ISSUE TITLE
Recent duplicates fix haven't deployed into npm

### ISSUE THREAD

**Issue by recallyourname** [benwinding/react-admin-firebase#279]
It seems that recent pull request were merged into master but never deployed to an NPM so the latest build has that duplicates issue. 

![image](https://github.com/benwinding/react-admin-firebase/assets/41914568/2be97ebb-9ad5-4377-a6de-b78800466e35)

How to work around it?

**Comment by T0jgli** [comment]
Yes, it would be good to rerun the job @benwinding

**Comment by tommylenz** [comment]
+1, this is a breaking bug imo. If I can be of any help @benwinding, please hit me up. Would love to see this bug gone.

**Comment by benwinding** [comment]
Finally got CI working and deployed as `react-admin-firebase@4.1.3`, apologies for the delay 😭

**Comment by recallyourname** [comment]
> Finally got CI working and deployed as `react-admin-firebase@4.1.3`, apologies for the delay 😭 

Thanks a lot!
