### ISSUE TITLE
Add option to enable/disable created_by and modified_by fields on documents

### ISSUE THREAD

**Issue by benwinding** [benwinding/react-admin-firebase#29]
As mentioned here: https://github.com/benwinding/react-admin-firebase/issues/25#issuecomment-497988353 by @tfesslerCWC,

It would be great to have `created_by` and `modified_by` fields on the document as it's created and updated.

**Comment by benwinding** [comment]
This is implemented in version `0.7.1`

**Comment by dhstack** [comment]
@benwinding Trying to find how to do this. I thought it would be in the config options, but I don't see it there. Is there an example I'm missing somewhere?
