### ISSUE TITLE
Error on create

### ISSUE THREAD

**Issue by hugofialho** [benwinding/react-admin-firebase#3]
Hi @benwinding, your job is ansome! react-admin-firebase works very fine!

When i create new doc i get this error on console:
The response to 'CREATE' must be like { data: { id: 123, ... } }, but the received data does not have an 'id' key. The dataProvider is probably wrong for 'CREATE'

I tried to redirect to list instead show, but the error ocurs and not redirect.

I  struggled studing your code, but didn't have much success. I think the error occur because the method add on firebase is async and you return data without id.
I resolved the error passing a constant id, but obviously is not the right think to do.

File firebaseDataProvider.js 
Method apiCreate changing line 157 

`return [2 /*return*/, {
          data: __assign({}, params.data)
}];`

`return [2 /*return*/, {
          data: __assign({}, params.data, { id: "temp"})
}];`

I am comming from C# and not have much experience with JS, i did any mistake using your lib or we have a issue?

**Comment by benwinding** [comment]
Thanks @hugofialho!

Assuming you resolved the problem, if not, let me know.

Cheers,
Ben
