### ISSUE TITLE
Importing 'firebase' explicitly imports ALL firebase components

### ISSUE THREAD

**Issue by wyattades** [benwinding/react-admin-firebase#33]
I think this imports the entirety of `firebase` in the following source files:
https://github.com/benwinding/react-admin-firebase/blob/0287eab133ea6c186fa62b04fce0c93b51aef625/src/providers/database/firebase/FirebaseWrapper.ts#L2
https://github.com/benwinding/react-admin-firebase/blob/88a15c9eacf28e698f5d71f70e09947944fdb6ce/src/providers/database/firebase/IFirebaseWrapper.ts#L3

I think the firebase team says it best:
> It looks like you're using the development build of the Firebase JS SDK. When deploying Firebase apps to production, it is advisable to only import the individual SDK components you intend to use.

**Comment by benwinding** [comment]
Thanks @wyattades,

That's a good point, there's been some refactoring in the past month and that must have slipped through. I also thought that `import * as firebase from 'firebase'` was the only line that triggered that message, but it seems `import { firestore } from "firebase";` triggers it too. 

Anyway, I will update the package with a fix (to remove that firebase warning) it in the next few days.

Cheers,
Ben

**Comment by benwinding** [comment]
Fixed in `react-admin-firebase@0.8.4`

Commit: 5d483b624225d594eb39653cbf7f9b4d4bb82102
