### ISSUE TITLE
Installation can't complete

### ISSUE THREAD

**Issue by rizals** [benwinding/react-admin-firebase#41]
please your support can't success for installation, I'm follow step by step user guide but can't success you can see picture below :

![error](https://user-images.githubusercontent.com/26091118/62416018-0d71ec00-b666-11e9-8b25-81b6789908f5.jpg)

![error 2](https://user-images.githubusercontent.com/26091118/62417095-12409b00-b67a-11e9-8437-b7d6b9e6d3bc.jpg)

**Comment by benwinding** [comment]
Hi @rizals,

Did you get the cloned repository working? Let me know if you need any help :+1: 

Cheers,
Ben
