### ISSUE TITLE
Multiple Image / File uploads from zero indexed array

### ISSUE THREAD

**Issue by wprk** [benwinding/react-admin-firebase#42]
Hi Ben,

Firstly just want to say a huge thank you for this library. Has enabled me to build out an admin panel for my firebase app really quickly.

I've noticed you've recently added file upload support for multiple files and it's working using the following format:
```
    <ArrayInput source="files">
        <SimpleFormIterator>
            <FileInput source="file" label="File">
                <FileField source="src" title="title" />
            </FileInput>
        </SimpleFormIterator>
    </ArrayInput>
```

Which stores the resulting data like this:
```
{
    files: [
        0: {
            file:  {
                src: "path_of_file",
                title: "name_of_file" 
           }
    ]
}
```

I was hoping instead to use the following format:

```
    <ImageInput source="images" label="Image" multiple={true}>
        <ImageField source="src" title="altText" />
    </ImageInput>
```

```
{
    files: [
        0: {
            src: "path_of_file",
            title: "name_of_file" 
        }
    ]
}
```

I'm going to have a go at creating a PR that will allow for both formats. Was there any reason you chose not to allow for this or were you not not aware of the usecase?

**Comment by benwinding** [comment]
Hi @wprk ,

Thanks for checking out the library, appreciate your contribution too!

> Was there any reason you chose not to allow for this or were you not not aware of the usecase?

To be honest, I was unaware that the multiple attribute existed on the `FileInput/ImageInput` fields. Your idea looks great, thanks for helping us out!

Cheers,
Ben
