### ISSUE TITLE
Sorting numbers

### ISSUE THREAD

**Issue by owocowyy** [benwinding/react-admin-firebase#45]
I have number of votes stored in firestore document as a number field `votes: 123` but I'm unable to properly sort those values. Datagrid always looks at the first digit on the left side.
```
export const NewsList = (props: any) => (
  <List {...props} filters={<NewsFilter />}>
    <Datagrid>
      <NumberField source="votes" />
    </Datagrid>
  </List>
);
```

Example result of ASC sort:
12
132
1900
22
3
800
9

I even created custom field to cast it to number
```
const VotesField = (props: any) => {
  const numberOfVotes = {
    [props.source]: parseInt(props.record[props.source], 10)
  };
  
  return <NumberField {...props} record={numberOfVotes} />;
};
```
Still same result.

**Comment by benwinding** [comment]
Hi @owocowyy,

Thanks for checking out the package, yes that seems annoying. I've just pushed a fix which allows numbers to sort correctly.

Please try the updated package **react-admin-firebase@0.8.8** and let me know if there's any issues.

Cheers,
Ben
