### ISSUE TITLE
Altering Firebase On Create

### ISSUE THREAD

**Issue by dragonkhoi** [benwinding/react-admin-firebase#48]
Hello, I'm trying to make a simple sign up app using react-admin and react-admin-firebase. My Firebase has a document of time slots, each with the timestamp and a bool whether it is filled or not. I have another document of signups, and am using the Create function to create new signups which contain a name and a timeslot. In Create for a new signup, it takes a ReferenceInput to a timeslot. I can get the timeslots to show up correctly in a SelectInput dropdown. If a user selects a timeslot and submits the form, I want to mark the bool in that timeslot in my Firebase to filled. Do I have to write a custom Save button, or how would I go about doing this? Or can you give an example of how to implement a handleSubmit function?

**Comment by benwinding** [comment]
Hey @dragonkhoi,
Thanks for checking out the package. This might be solved using pieces from the base `react-admin` framework. [This article](https://marmelab.com/blog/2018/08/27/react-admin-tutorials-custom-forms-related-records.html) explains how to add custom save buttons and  popups etc. Does this help for your problem?
Cheers,
Ben

**Comment by dragonkhoi** [comment]
Incredible. Was looking through this earlier and didn't know if it was what I was looking for. Thank you for confirming. After spending time with it, I've implemented a custom onSubmit in a custom SimpleForm component. Thanks.
