### ISSUE TITLE
Wrong type stored in Firebase on Edit

### ISSUE THREAD

**Issue by keylook** [benwinding/react-admin-firebase#51]
Hi, I don't have much experience with JS or React so my question might not be exactly related to the library implementation but in my previous version of admin panel (without this library) everything worked correctly.

I have a simple form with text input. The source of this field is Number in Firebase, but on edit value from input is passed as String. On edit action the type is being changed to String. 

```
...
<TextInput source = "position" label = "# Position"/>
...
```
Before edit
```position: 5```
After edit
```position: "5"```

Is this library issue and if not, what could be done to prevent this behavior? Thank you.

**Comment by benwinding** [comment]
Did you get this working? Cheers for checking out the package anyway!

**Comment by keylook** [comment]
@benwinding yes. As I suspected the issue had nothing to do with the library itself. An obvious answer was in the question. I expected **Number**, but was using **Text**Input. I changed it to `NumberInput` and it worked as expected.
