### ISSUE TITLE
getAbsolutePath returns wrong path 

### ISSUE THREAD

**Issue by x5engine** [benwinding/react-admin-firebase#52]
HI there,
getAbsolutePath returns wrong path which lead to resource not found then collection of undefined.
https://github.com/benwinding/react-admin-firebase/blob/dee10e43048aa23b148d5efdd7b03ea2ff3a3606/src/misc/pathHelper.ts

my config is like so:

const options = {
  logging: true,
  debug: true,
  rootRef: 'root_collection/GXLak3jr1WMSN8SGijoH',
  watch: ["posts"]
}

https://github.com/benwinding/react-admin-firebase/blob/dee10e43048aa23b148d5efdd7b03ea2ff3a3606/src/providers/database/ResourceManager.ts#L75

![image](https://user-images.githubusercontent.com/12363020/65828834-1f9f8d80-e297-11e9-9b45-ca49bd40c6ef.png)
![image](https://user-images.githubusercontent.com/12363020/65828837-30e89a00-e297-11e9-817a-1906f2d0512c.png)

it should be '/root_collection/GXLak3jr1WMSN8SGijoH/posts/ not 'root_collection/GXLak3jr1WMSN8SGijoH' which is the wrong path,

the slice you are doing in the aboslute path helper is the cause I think

**Comment by benwinding** [comment]
@x5engine Thanks for reporting this :+1: That's embarrassing, I'll look right into it

**Comment by benwinding** [comment]
What version are you running? It seems to work as expected on the latest version ... `0.8.10`

Please let me know a reproducible case, and I'll look into it a bit more

**Comment by x5engine** [comment]
thanks for the response! this is the latest version! I don't know what happened but seems it's finding the right path...

**Comment by benwinding** [comment]
Great to hear, if theres any other issues, let me know!

**Comment by x5engine** [comment]
it's not finding the right path! this is not solved sorry for that typo! @benwinding  please test it
