### ISSUE TITLE
Map custom field to id?

### ISSUE THREAD

**Issue by nsdub** [benwinding/react-admin-firebase#53]
React-admin queries on the basis of the `id` of a record. My records instead use `uid`. I'd like to map `uid` to the `id` field. How might I accomplish this?

[Here's](https://github.com/marmelab/react-admin/issues/142) this same question asked on the react-admin repo and the maintainer states that this should be handled by the REST client.

**Comment by nsdub** [comment]
For future folks facing the same issue, you'll want to modify `ResourceManager`, specifically [this line](https://github.com/benwinding/react-admin-firebase/blob/2746d43c26da35b57203796ca78dd083818c4e29/src/providers/database/ResourceManager.ts#L109).

(I ended up forking and hardcoding a solution to fit my needs.)

**Comment by benwinding** [comment]
@nsdub Thanks for checking this out, did you get a working implementation by changing that line? I could add it as a flag in the configuration object if you'd like.
