### ISSUE TITLE
Any example on how to upload an image to Firebase storage

### ISSUE THREAD

**Issue by zhouhao27** [benwinding/react-admin-firebase#56]
I'd like to now how to upload an image to the Firebase storage and use the returned url in ImageField? Thanks.

**Comment by zhouhao27** [comment]
I think you save everything into firebase storage.

**Comment by punov** [comment]
Same question

**Comment by gypsicoder** [comment]
@zhouhao27  You closed the issue. Will you please share how you solved. Please share your example here. It will help others who wants the example.

**Comment by benwinding** [comment]
Hey guys,

The file upload works using Firebase Storage and uses all the standard react-admin components.
- See here for more details: https://marmelab.com/react-admin/Fields.html#filefield

**Example usage**
Put this field in an edit/create view.
``` html
<FileInput source="file" label="File" accept="application/pdf">
  <FileField source="src" title="title" />
</FileInput>
```
When you click submit the files will be uploaded to the default cloud storage, which you can view here:
![image](https://user-images.githubusercontent.com/11782590/84214892-e72da000-ab03-11ea-90a2-67a0f504b4e1.png)

The path of the file is related to the document that you added for example:

| Firestore Document | File Field (source) | Stored File                                             |
|--------------------|---------------------|---------------------------------------------------------|
| /posts/1234567     | image_file          | gs://comm-unstable.appspot.com/posts/1234567/image_file |

Let me know if there's any issues/questions.

Cheers,
Ben

**Comment by gypsicoder** [comment]
@benwinding  thank you for your help. Yes, I have checked that site and used in my project to upload images. But, the problem I faced is when I upload image it put the url 
in an object for example for your example it will put an object in the document like this
image_file: {
src: 'some_image_url',
title: 'probably the file name'
}
What if I want to just put the url in the main source field image_file ?

**Comment by benwinding** [comment]
> What if I want to just put the url in the main source field image_file ?

Sorry, this functionality not possible and is beyond the scope of react-admin-firebase and probably react-admin too. 

The reason it's an object is to preserve the url and the filename too. 

Is there a specific reason it cannot be an object?
