### ISSUE TITLE
Package not build when I fork your repository

### ISSUE THREAD

**Issue by zhouhao27** [benwinding/react-admin-firebase#58]
I'm trying to migrate to react-admin v3. So I forked your repository. After that, when I `yarn add  https://github.com/zhouhao27/react-admin-firebase`, the result is:

<img width="222" alt="Screenshot 2019-10-31 at 10 55 46 PM" src="https://user-images.githubusercontent.com/8099731/67958135-9da5da00-fc31-11e9-9198-11e476b85c0d.png">

But when I `yarn add react-admin-firebase`, the result is:

<img width="177" alt="Screenshot 2019-10-31 at 10 51 40 PM" src="https://user-images.githubusercontent.com/8099731/67958166-ac8c8c80-fc31-11e9-8581-7987c13813a0.png">

Apparently my repository is not build when I added to my project. What is the possible reason? Thanks.

By the way, I didn't change anything yet after I forked your repository.

**Comment by benwinding** [comment]
Hi @zhouhao27,
The reason it wasn't working, was that the **dist** folder, was not tracked in git. So I just added it the repository.

It should work now, if you pull in the changes from this repo to your fork. You should be able to use the command.

`yarn add https://github.com/zhouhao27/react-admin-firebase`

Cheers,
Ben

**Comment by zhouhao27** [comment]
Great, thanks! I though should publish to npm repository.
