### ISSUE TITLE
Support for filters in List

### ISSUE THREAD

**Issue by kdabir** [benwinding/react-admin-firebase#6]
React-Admin supports `filters` property in `List` component. When using react-admin-firebase as data provider, adding `filters` to `List` doesn't work. I checked the source and noticed `params.filter` is never used in the provider.

references: 
https://marmelab.com/react-admin/List.html#filters
https://firebase.google.com/docs/firestore/query-data/queries

**Comment by macscripter** [comment]
Is it planned to support filters in the next releases?

**Comment by benwinding** [comment]
Apologies for the late reply, Filtering is now implemented in version 0.3.0.

Please let me know if there's any issues or other concerns you can see.

**Comment by imikemiller** [comment]
@benwinding thats great thanks a lot, add a tip jar so I can buy you a beer!

**Comment by benwinding** [comment]
@imikemiller no worries mate!
I'll think about it, but honestly I think the thank you means more to me :)
Let me know if there's any other issues or concerns,
Ben
