### ISSUE TITLE
Prettier rules 

### ISSUE THREAD

**Issue by LaszloDev** [benwinding/react-admin-firebase#60]
hey @benwinding, would you be open to add some prettier rules to the project, so we have a definition for the code formatting? 
The project does missing some consistency of the code formatting in few files. Like ' or " quoation or spacings. A prettier config would set a default with we can agree on and so have a common stying definition when contributing to the package.

I can open a PR if you are open to it.
Thanks Laszlo

**Comment by benwinding** [comment]
Hi @LaszloDev,

Great idea, added `.prettierrc` in commit: 4fcd77b099309ced4e554d2825376997697a59d7

If you want you can submit a PR to update it and ensure consistent formatting.

Cheers,
Ben
