### ISSUE TITLE
pagination doesn't seem to work with filter

### ISSUE THREAD

**Issue by SangilYun** [benwinding/react-admin-firebase#61]
Hi!
first of all thank you for making this awesome package. It makes my life a lot easier
But one thing i noticed using react-admin and react-admin-firebase is that when using filter, pagination seems to not working.

Below is an example captured from demo app (https://react-admin-firebase-1.web.app/#/posts)
![image](https://user-images.githubusercontent.com/35569652/69035414-f7c2df80-0a26-11ea-9680-1360abbe68b2.png)

There are total 6 and each page shows 5, hence there are total 2pages

![image](https://user-images.githubusercontent.com/35569652/69035652-8172ad00-0a27-11ea-9892-aaa98252c6dd.png)
but when i seach for t2, even though there are only one post that matches search keyword, the pagination still shows us there are 2 pages and if i click page 2, it just shows me an empty page.

shouldn't it show us only 1 page since the search result fits in one page?
Thank you !

**Comment by LaszloDev** [comment]
I do see an issue with the search generally. As soon as we moved to Support React Admin 3, I will have a look and see if I can find the problem.

**Comment by benwinding** [comment]
Hi @SangilYun,

Thanks for spotting that, yes the **total** items count _before_ filtering was being returned. Should be working properly in: `react-admin-firebase@3.1.3`.

Cheers,
Ben
