### ISSUE TITLE
ability to disable metadata

### ISSUE THREAD

**Issue by mlipscombe** [benwinding/react-admin-firebase#62]
Currently, several metadata fields are automatically created/updated, like `createdate`, `lastupdate`, `createdby` and `updatedby`.  This leaks information (for example, the email addresses of admin users) into documents that may be publicly accessible, and should be able to be disabled.

I can make a PR to add an option like `nometadata` if that would be acceptable.

**Comment by benwinding** [comment]
Hi Mark,

That's a great idea, there should be an option to switch that functionality
off at least.

Male a PR and I'll deploy it as soon as I can.

Cheers,
Ben

**Comment by dhstack** [comment]
I agree this would be beneficial. Or even being able to pass an array of fields you want to use (in case you want `lastupdate`, but not the `updatedby`, for example). I'm also an advocate of changing the names to be camelCase for easier readability. Like this:
- `createdate` -> `createDate`
- `lastupdate` ->`lastUpdate`
- `createdby` -> `createdBy`
- `updatedby` -> `updatedBy`

**Comment by RWOverdijk** [comment]
I agree. This is a privacy issue and makes the whole library unusable. @mlipscombe did you end up making a PR?

@benwinding what's the fastest way to just disable this altogether?

**Comment by benwinding** [comment]
Hey Guys,

Yes this has been an annoying thing for a while. It's now an option in the options object:
``` js
const options = {
  // Disable the metadata; 'createdate', 'lastupdate', 'createdby', 'updatedby'
  disableMeta: true
}
```
Available in `react-admin-firebase@3.1.0`

@dhstack maybe we should open another issue for renaming the field names.

Let me know if there's any issues,

Cheers,
Ben

**Comment by RWOverdijk** [comment]
@benwinding Thanks for your quick reply :) This looks great, because we can already add hooks ad add our own fields if we want.

**Comment by dhstack** [comment]
@benwinding This works, thanks!

**Comment by mattsears18** [comment]
is it possible to rename the metadata fields with custom names?

**Comment by benwinding** [comment]
Hi @mattsears18, 
No it's currently not possible. You can change the casing of the meta data fields though.

``` js
const options = {
  // Casing for meta fields like 'createdby' and 'updatedby', defaults to 'lower' 
  // options are: 'lower' | 'camel' | 'snake' | 'pascal' | 'kebab'
  metaFieldCasing: 'lower'
}

const dataProvider = FirebaseDataProvider(config, options);
```

**Comment by mattsears18** [comment]
@benwinding thanks! that will work for now.
