### ISSUE TITLE
Support for initialValues prop in Create?

### ISSUE THREAD

**Issue by nsdub** [benwinding/react-admin-firebase#68]
React-admin lets you pass in an `initialValues` object to `<SimpleForm>` to specify a set of default values when creating a record ([ref](https://marmelab.com/react-admin/CreateEdit.html#default-values)). 

Does `react-admin-firebase` contain support for the `initialValues` prop?

In my project, the object passed to `initialValues` is ignored. Example:

```
const defaultValues = {
      createdAt: new Date().getTime(),
      ....
    }

<SimpleForm initialValues={defaultValues}>
      <TextInput source="first_name" />
</SimpleForm>
```

We'd expect the newly created record to contain the fields in `defaultValues`.

**Comment by benwinding** [comment]
Hi @nsdub 

Currently this feature is not implemented. 

But `react-admin-firebase` automatically creates the following fields in the Firestore document:

``` typescript
// on create document
createdate: Date,
createdby:  string (email),

// on update document
lastupdate: Date,
updatedby:  string (email)
```

Hope this helps, we'll hopefully get to a few of these issues in the coming weeks.

Cheers,
Ben

**Comment by nsdub** [comment]
Thanks for the note, Ben. As a temporary workaround, I'll just go ahead and use disabled fields with default values. And thank you for this package -- it's saved me a ton of heartache

**Comment by dhstack** [comment]
@nsdub It looks like this feature is implemented in https://github.com/benwinding/react-admin-firebase/pull/67 and in the https://github.com/benwinding/react-admin-firebase/tree/upgrade-to-react-admin-v3 branch
