### ISSUE TITLE
Add this project to react-admin docs

### ISSUE THREAD

**Issue by dhstack** [benwinding/react-admin-firebase#72]
There's a list of DataProviders in the react-admin docs. It might be a good idea to put this project in there as it's the most active and popular. It would help to make this project more visible too.

https://marmelab.com/react-admin/DataProviders.html

**Comment by dhstack** [comment]
I assume you'd need to reach out to marmelab directly to get it added there.

**Comment by steurt** [comment]
@dhstack I agree. Though I think it would be wise to wait until the `react-admin` v3 is finished and available. So it won't end up in the section:
> Due to breaking changes in v2, these providers are no longer working.

When v3 is available, one can simply create a pull request on `react-admin` with a change to the docs.

**Comment by Immortalin** [comment]
On the react admin landing page, the Firebase logo is linked to https://github.com/aymendhaya/ra-data-firebase-client/blob/master/README.md

**Comment by benwinding** [comment]
> I assume you'd need to reach out to marmelab directly to get it added there.

I have reached out before with a PR to add it to the docs before, [but unfortunately it was rejected ](https://github.com/marmelab/react-admin/pull/3232) and I was met with fairly negative feedback for developing a dataprovider that already existed :disappointed: .

But this project has picked up much more adoption since then, so maybe I'll try again...

**Comment by rafalzawadzki** [comment]
Hi @benwinding, creator of [ra-data-firestore-client](https://github.com/rafalzawadzki/ra-data-firestore-client) here. As your project is better maintained and adopted more, I decided to discontinue mine. 

I gave appropriate notice on `ra-data-firestore-client` & redirect to your project now. I think you can submit an another PR to `react-admin` docs and quote this comment if needed :)

**Comment by benwinding** [comment]
Hi @rafalzawadzki,

Thanks for reaching out! It looks like we both created DataProviders around the same time in late 2018 (great minds think a like :wink:). 

Thanks for letting me know, I'll submit a PR to the `react-admin` docs and update this issue.

Cheers,
Ben
