### ISSUE TITLE
Upload in nested fields : Function DocumentReference.set() called with invalid data. Unsupported field value: a custom File object

### ISSUE THREAD

**Issue by simokhalil** [benwinding/react-admin-firebase#73]
Hi there,

Thank you for this awesome plugin !

I am stuck when I try to upload files in nested objects, I get this error : 
`Function DocumentReference.set() called with invalid data. Unsupported field value: a custom File object`

My structure is as follows : 

```
classes
  |_ title
  |_ sections
    |_ mySection
      |_ items[]
        |_ image       <---- Here is my file
          |_ url
```

It'd work fine if my structure was like : 
```
classes
  |_ title
  |_ items[]
    |_ image
      |_ url
```

After a little bit digging into it, I think the problem is that the `parseDataAndUpload()` function only looks for file fields in the root of the created/edited object, but I'm not sure...

Can someone point me to a solution please ?

**Comment by simokhalil** [comment]
Fixed in PR #74

**Comment by dhstack** [comment]
Having this issue too. Thanks for the fix @simokhalil!

**Comment by benwinding** [comment]
Should be fixed now, but let me know if there's any issues with this.
