### ISSUE TITLE
Extra 'id' field created in Firestore when setting a custom document id

### ISSUE THREAD

**Issue by dhstack** [benwinding/react-admin-firebase#76]
There's an extra `id` field that's created in a Firestore document when a custom document ID is set as described [here](https://github.com/benwinding/react-admin-firebase/issues/24#issuecomment-502360662).

![image](https://user-images.githubusercontent.com/2013388/74052391-c7e10380-49a7-11ea-9c18-4082504e8286.png)

**Comment by benwinding** [comment]
Hi @dhstack,

Yes this is a good, point. The option `dontAddIdFieldToDoc` has been added to the options and will prevent this behaviour.

This was deployed in version `react-admin-firebase@3.1.2`

Cheers :+1:,
Ben

**Comment by dhstack** [comment]
@benwinding Looks like this works, thanks!
