### ISSUE TITLE
Cannot create/edit data when firebase is in dependencies

### ISSUE THREAD

**Issue by MichalKalita** [benwinding/react-admin-firebase#78]
Hi, it is great project! Thanks for that.

When I try to update or create any item, I get a error
`Function DocumentReference.set() called with invalid data. Unsupported field value: a custom ServerTimestampFieldValueImpl object (found in field createdate)`

The source of problem is in line https://github.com/benwinding/react-admin-firebase/blob/upgrade-to-react-admin-v3/src/providers/database/FirebaseClient.ts#L86

Firebase version 7.8.1
React-admin 3.2.1
React-admin-firebase `github:benwinding/react-admin-firebase#upgrade-to-react-admin-v3`

**Comment by MichalKalita** [comment]
I found a problem. I had a firebase in dependencies in my project. It makes conflict. I just remove `firebase` from my dependencies and create/update works.

Maybe `firebase` should be a peer dependency of this project?

**Comment by dhstack** [comment]
Might have to change [package.json](https://github.com/benwinding/react-admin-firebase/blob/master/package.json) to include the `^` character for firebase dependency.

```
"firebase": "^6.1.x",
```

**Comment by benwinding** [comment]
Hey @MichalKalita, 
That's a good point, so we made firebase is a peer dependency. So you need to have the `firebase@7.9.x` in your app's `package.json` file.

Just published version `3.1.0`

Cheers,
Ben
