### ISSUE TITLE
Get current user email

### ISSUE THREAD

**Issue by aaronat1** [benwinding/react-admin-firebase#79]
How can I get current user logged? For example user email. I want to use this email to use in Filter. For example:

```
export const SMSList = (props) => (
  <List {...props} filter={{ createdby: currentUser.email}}....
```
Regards

**Comment by dhstack** [comment]
If you're using the v3 beta you can use the following:

```
import { FirebaseAuthProvider } from 'react-admin-firebase';

const authProvider = FirebaseAuthProvider(firebaseConfig, firebaseOptions);

// Get current user
const user = authProvider.checkAuth();
user.then(user => {
  console.log('Email: ' + user.email);
});
```

You can also get other properties form this object like `user.displayName` or `user.uid`

**Comment by benwinding** [comment]
Thanks @dhstack! 

Yes that's the intended method of retrieving the current user. You also have access to the following properties (and more):
![image](https://user-images.githubusercontent.com/11782590/75036034-d3ccd980-5500-11ea-9c4b-480d57b1c5c4.png)
More info: https://firebase.google.com/docs/auth/web/manage-users#get_a_users_profile 

Cheers,
Ben
