### ISSUE TITLE
how can I use with real time database not with firestore?

### ISSUE THREAD

**Issue by konyilwin** [benwinding/react-admin-firebase#81]
Hi there,
I want to use this with real time database not with firestore. Is that possible? If yes, how can I do that?
any suggestion or tutorial pls.

**Comment by benwinding** [comment]
Hi @konyilwin,
Currently this library only supports the **Firestore** database provided by Firebase. There's no plans to include this in the future, but if someone wants to submit a Pull Request, I'll consider it.
Cheers,
Ben
