### ISSUE TITLE
Fetch user for role/permissions in app

### ISSUE THREAD

**Issue by Rawphs** [benwinding/react-admin-firebase#83]
Hey, cool plugin, loving it so far! Quick question though...

I have a users collection with (surprise, surprise) users, and I want to fetch the authenticated user's document so I can use it in App.js to decide the permissions. Some resources shouldn't be visible to all users so it would be nice to selectively add/remove resources in render.

What's the recommended way to do this? I was going to include firebase and fetch the user in componentDidMount but it feels... off.

Any advice?

**Comment by benwinding** [comment]
Hey @Rawphs,

Thanks for checking it out! So you can fetch the current `UserCredentials` using the `AuthProvider`. This will give you the user details (uid, email, displayName):

``` js
import { FirebaseAuthProvider } from 'react-admin-firebase';

const authProvider = FirebaseAuthProvider(firebaseConfig, firebaseOptions);

authProvider.checkAuth().then(user => {
  console.log('Email: ' + user.email);
  console.log('   UID: ' + user.uid);
});
```

You should also checkout `Custom Claims`, which are special fields on the `UserCredentials` object that you can only set on the server, which makes them pretty safe.

Something like `user.getIdTokenResult()` to get the claims.

Custom Claims Method: https://firebase.google.com/docs/reference/js/firebase.User#getidtokenresult
Custom Claims Result: https://firebase.google.com/docs/reference/js/firebase.auth.IDTokenResult

Anyway, hope this helps!

Cheers,
Ben

**Comment by Rawphs** [comment]
Sorry, I thought I had replied already. Thank you for this!
