### ISSUE TITLE
Failed compile: Cannot find SourceMap 'mutationobserver.map'

### ISSUE THREAD

**Issue by aaronat1** [benwinding/react-admin-firebase#85]
I follow this steps with lattest version:

    1. git clone https://github.com/benwinding/react-admin-firebase
    2. yarn && yarn watch
    3 (open another terminal)
    4. cd src-demo && yarn && yarn start

This is the error:

Emitted value instead of an instance of Error) Cannot find SourceMap 'mutationobserver.map': Error: Can't resolve './mutationobserver.map' in '/Users/mac/aaronasencio/SIC4Change/EmilpaV2/react-admin-firebase/src-demo/node_modules/@sheerun/mutationobserver-shim/dist'

**Comment by benwinding** [comment]
Hey @aaronat1,

Thanks for checking out the package and reporting the issue :+1: 

Yes, that's been a bit of an annoying workflow, so I changed this library to use `gulp`, which makes things simpler in development. So `git pull origin master` for the latest changes, Instructions have been updated too:
```
git clone https://github.com/benwinding/react-admin-firebase
yarn
yarn start-demo
```
(All in the same terminal window)

Cheers,
Ben
