### ISSUE TITLE
Unexpected logout when creating a doc with same id after error

### ISSUE THREAD

**Issue by dhstack** [benwinding/react-admin-firebase#91]
When trying to create a document with the same ID, `react-admin-firebase` now throws an error saying the id is already in use as of PR #86, but it now also logs you out whenever that error is thrown as described in related issue #77.

**Comment by 5achinJani** [comment]
Any fix/workaround for this?

**Comment by dhstack** [comment]
Not as far as I kow

**Comment by benwinding** [comment]
Finally got this fixed, the problem was due to the `AuthProvider` not correctly implementing the `HandleAuthError` function which triggers an `Auth failed` by default.

![Peek 2020-04-14 11-45](https://user-images.githubusercontent.com/11782590/79178907-9a9c5000-7e45-11ea-9970-3935a2dc8acd.gif)

**Comment by 5achinJani** [comment]
Hey thanks @benwinding  for the update. I saw the code you added for it.  `HandleAuthError ` now checks for code status in errorHttp object. Here in my case I'm using `graphql-shield` on the server and this `errorHttp ` doesn't contain `status` in it hence it is causing the logout cause the promise gets rejected. Do you have any idea how to make sure that my graphql-shield or apollo server passes the status code information to the client in the `errorHttp ` object? 
![image](https://user-images.githubusercontent.com/23077544/79209443-11931200-7e61-11ea-95ed-44cb3ef1da7c.png)

**Comment by 5achinJani** [comment]
I've added an override for `checkError` to handle this for graphql :
```ts
export const firebaseAuthProvider = FirebaseAuthProvider(config, {
  persistence: "local",
  logging: true
});

export const authProvider = {
  ...firebaseAuthProvider,
  checkError: error => {
    console.log({ error });
    return Promise.resolve(error);
  }
};
```
Here I can add checks for graphql error codes based on this apollo docs
https://www.apollographql.com/docs/apollo-server/data/errors/#codes
It'd be better if you support the graphql error codes like the basic ones like `UNAUTHENTICATED` in your `checkError` function as an out-of-the-box support for graphql errors and people can anyway override the `checkError` to plug in their custom error codes checks.

**Comment by benwinding** [comment]
Hi @5achinJani ,

Glad to hear you got it sorted out. Just wondering, what's the architecture of your app? like, how are you using `graphql` with `react-admin-firebase`?

> It'd be better if you support the graphql error codes like the basic ones like UNAUTHENTICATED in your checkError function as an out-of-the-box support for graphql errors and people can anyway override the checkError to plug in their custom error codes checks.

Below is the function which checks the error and is giving you trouble. 

https://github.com/benwinding/react-admin-firebase/blob/f601cb8505e8d6f990d171ab466c764093b67079/src/providers/AuthProvider.ts#L65-L72

If you'd like to contribute a solution which handles your use-case with `graphql` responses, I'd be happy to merge it in.

Kind regards,
Ben

**Comment by 5achinJani** [comment]
Sure thing ben I'll :) I'm using prisma data-source for dataProvider and react-admin-firebase only for the authProvider and it is working pretty great. Thanks for this package. :)

**Comment by dhstack** [comment]
Tested and the fix works for me. Thanks @benwinding!
