### ISSUE TITLE
Logging option has no effect on local development

### ISSUE THREAD

**Issue by dhstack** [benwinding/react-admin-firebase#92]
When developing locally, regardless of if `logging` is `true` or `false` in the `react-admin-firebase` options, the logs are output. It may have to do with this line (46) in `src/misc/logger.ts`:

`if ((config && config['debug']) || options.logging) {`

Not sure what `config['debug']` is doing.

**Comment by benwinding** [comment]
Hey @dhstack,

Thanks for picking that up, yeah I thought it was working a while ago, for some reasons `var DEBUG` was not a global variable anymore. 

Anyway it's fixed now, using the local browser storage to persist state. ab3162834e28fbb9853eca7e23a4e8347bd37f61

Also config['debug'] is a deprecated way of enabling debug mode (I like to keep things backwards compatible but it gets messy) should be deployed in version `3.1.5`

Cheers,
Ben
