### ISSUE TITLE
Import CSV

### ISSUE THREAD

**Issue by aaronat1** [benwinding/react-admin-firebase#94]
Is there way to import csv data? I can see an Export Button but I can not see the posibility to import data.

**Comment by dhstack** [comment]
Doesn't look like this is part of the core `react-admin` package.

See: https://github.com/marmelab/react-admin/issues/3809

Alternatively, you can import data directly into Firebase using [one of these methods](https://stackoverflow.com/questions/33930915/how-to-import-csv-files-into-firebase/47581258), then simply use `react-admin-firebase` to read the data and manipulate as usual.

**Comment by benwinding** [comment]
Hey Guys,

Yeah this has always been a bit of a pain, so I implemented the solution from @Odonno into an npm package (`react-admin-import-csv`) Give it a go and let me know if there's any issues.

https://github.com/benwinding/react-admin-import-csv 

Cheeers,
Ben
