### ISSUE TITLE
Listen AuthProviderChanges

### ISSUE THREAD

**Issue by sic4change** [benwinding/react-admin-firebase#97]
Hi,

how can I listen changes in AuthProvider? For example when user login, logout....

Regards

**Comment by benwinding** [comment]
Hi @sic4change,

You can use the [`useAuthState()`](https://github.com/marmelab/react-admin/blob/master/docs/Authentication.md#useauthstate-hook) hook. 

> You can render different content depending on the authenticated status.
> ``` ts
> import { useAuthState, Loading } from 'react-admin';
> 
> const MyPage = () => {
>     const { loading, authenticated } = useAuthState();
>     if (loading) {
>         return <Loading />;
>     }
>     if (authenticated) {
>         return <AuthenticatedContent />;
>     } 
>     return <AnonymousContent />;
> };
> ```
> 

Cheers,
Ben
