### ISSUE TITLE
Get AuthProvider in DataProvider

### ISSUE THREAD

**Issue by RWOverdijk** [benwinding/react-admin-firebase#98]
I'd like to add default arguments to certain queries.

I have big buckets of data which is mixed for multiple users. I want the user to only attempt to fetch the records they own because otherwise firestore will throw a permission error.

Ownership is indicated via a prop on the document (user's id) and therefor I'd like to simply add the user's id to all fetches (and creates).

To do this, I think I'll need access to the authProvider and wrap the dataProvider. How should I go about doing this?

And will this cause problems with onSnapshot? Do they automatically stop listening when a user is logged out for example?

And also also, is my approach ideal? Or would you advise a different one?

**Comment by dvasdekis** [comment]
[I've achieved a similar integration here](https://github.com/dvasdekis/react-admin-hasura-firebase/blob/master/src/App.js), which defines the data provider using the response from the auth provider.

Take a look and let me know what's missing!

**Comment by RWOverdijk** [comment]
It's not exactly the same because the auth state can change during a session.

In any case, I've solved this by patching the data provider 😄
