### ISSUE TITLE
Filter between date values

### ISSUE THREAD

**Issue by sic4change** [benwinding/react-admin-firebase#99]
Hi,
How can I filter dates that are within a range? In other words, having two date filters, one that allows entering the start date and another that allows entering the end date and obtaining the dates within that range in the list. 

Thanks for everything. 
Cheers

**Comment by benwinding** [comment]
Yeah that's not too hard to do, you just need add the `collectionQuery` field to the filter prop on the List Component. I'm not entirely sure on how to make it dynamic though.

``` js
export const PostList = props => (
  <List
    {...props}
    filter={{ 
      collectionQuery: c => c
        .where('date', '<=', START_DATE)
        .where('date', '>=', END_DATE)  
    }}
  >
    <Datagrid>
      <TextField source="id" />
```

Cheers,
Ben
